# Generated by Django 6.0.8 on 2026-09-29 05:16

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="logo",
            field=models.ImageField(
                blank=True,
                upload_to="brands/%Y/%m/",
                validators=[core.models.validate_brand_image_size],
            ),
        ),
    ]
