# Generated by Django 6.0.8 on 2026-09-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_documenttype_notification_persondocument_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="notification",
            name="last_error",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="organization",
            name="email_from",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="organization",
            name="email_provider",
            field=models.CharField(
                choices=[
                    ("mailjet", "Mailjet"),
                    ("ses", "Amazon SES"),
                    ("postmark", "Postmark"),
                ],
                default="mailjet",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="sms_from",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="organization",
            name="sms_provider",
            field=models.CharField(
                choices=[("sns", "Amazon SNS"), ("twilio", "Twilio")],
                default="sns",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="mobile_phone",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
