# Generated by Django 6.0.8 on 2026-09-29 05:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_notification_attempts_notification_last_error_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entity",
                    models.CharField(
                        choices=[
                            ("branches", "Branches"),
                            ("people", "People"),
                            ("clients", "Clients"),
                            ("sites", "Sites"),
                            ("credentials", "Credentials"),
                            ("training", "Training"),
                            ("shifts", "Shifts"),
                        ],
                        max_length=30,
                    ),
                ),
                ("source_name", models.CharField(max_length=255)),
                ("source_hash", models.CharField(max_length=64)),
                ("rows", models.JSONField(default=list)),
                ("errors", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("preview", "Preview"),
                            ("invalid", "Invalid"),
                            ("applied", "Applied"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_batches",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "entity", "source_hash"),
                        name="unique_import_source_in_org",
                    )
                ],
            },
        ),
    ]
