# Generated by Django 6.0.8 on 2026-09-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_persondocument_archived_at_dispositionrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="mfa_required_roles",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
