# Generated by Django 6.0.8 on 2026-09-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_organization_mfa_required_roles"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationdomain",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending verification"),
                    ("verified", "Verified"),
                    ("failed", "Verification failed"),
                    ("suspended", "Suspended"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="organizationdomain",
            name="verification_token",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AddField(
            model_name="organizationdomain",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
