# Generated by Django 6.0.8 on 2026-09-29 13:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_database_tenant_guards"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="dark_accent_color",
            field=models.CharField(
                default="#5EEAD4",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#[0-9A-Fa-f]{6}$",
                        "Use a six-digit hex color, such as #16324F.",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="dark_mode_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="dark_primary_color",
            field=models.CharField(
                default="#0B1F33",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#[0-9A-Fa-f]{6}$",
                        "Use a six-digit hex color, such as #16324F.",
                    )
                ],
            ),
        ),
        migrations.CreateModel(
            name="BrandVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("snapshot", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="brand_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brand_versions",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "version"),
                        name="unique_brand_version_in_org",
                    )
                ],
            },
        ),
    ]
