# Generated by Django 6.0.8 on 2026-09-29 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_organization_dark_accent_color_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomFieldDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("key", models.SlugField(max_length=60)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("date", "Date"),
                            ("boolean", "Yes / no"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("required", models.BooleanField(default=False)),
                ("sensitive", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DocumentAcknowledgment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("signature_name", models.CharField(blank=True, max_length=160)),
                ("statement", models.CharField(max_length=255)),
                ("document_sha256", models.CharField(max_length=64)),
                ("ip_hash", models.CharField(max_length=64)),
                ("acknowledged_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PersonCustomValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PersonHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("changes", models.JSONField(default=dict)),
                ("snapshot", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="person",
            name="address_line1",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="person",
            name="address_line2",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="person",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="person",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="emergency_contact_name",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="person",
            name="emergency_contact_phone",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="person",
            name="employee_id",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="person",
            name="hire_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="hourly_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="job_title",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="person",
            name="postal_code",
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name="person",
            name="state",
            field=models.CharField(default="TX", max_length=2),
        ),
        migrations.AddField(
            model_name="person",
            name="termination_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="person",
            constraint=models.UniqueConstraint(
                condition=models.Q(("employee_id", ""), _negated=True),
                fields=("organization", "employee_id"),
                name="unique_employee_id_in_org",
            ),
        ),
        migrations.AddField(
            model_name="customfielddefinition",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_field_definitions",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="documentacknowledgment",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="acknowledgments",
                to="core.persondocument",
            ),
        ),
        migrations.AddField(
            model_name="documentacknowledgment",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="document_acknowledgments",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="documentacknowledgment",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="document_acknowledgments",
                to="core.person",
            ),
        ),
        migrations.AddField(
            model_name="documentacknowledgment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="document_acknowledgments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="personcustomvalue",
            name="definition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="values",
                to="core.customfielddefinition",
            ),
        ),
        migrations.AddField(
            model_name="personcustomvalue",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="person_custom_values",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="personcustomvalue",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custom_values",
                to="core.person",
            ),
        ),
        migrations.AddField(
            model_name="personhistory",
            name="changed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="personhistory",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="person_history",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="personhistory",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history",
                to="core.person",
            ),
        ),
        migrations.AddConstraint(
            model_name="customfielddefinition",
            constraint=models.UniqueConstraint(
                fields=("organization", "key"), name="unique_custom_field_key_in_org"
            ),
        ),
        migrations.AddConstraint(
            model_name="documentacknowledgment",
            constraint=models.UniqueConstraint(
                fields=("document", "person"), name="unique_document_acknowledgment"
            ),
        ),
        migrations.AddConstraint(
            model_name="personcustomvalue",
            constraint=models.UniqueConstraint(
                fields=("person", "definition"), name="unique_custom_value"
            ),
        ),
    ]
