# Generated by Django 6.0.8 on 2026-09-29 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_customfielddefinition_documentacknowledgment_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditRedaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fields", models.JSONField(default=list)),
                ("reason", models.TextField()),
                ("legal_basis", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="auditevent",
            name="event_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="auditevent",
            name="previous_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="organization",
            name="audit_retention_days",
            field=models.PositiveIntegerField(default=2555),
        ),
        migrations.AddConstraint(
            model_name="auditevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("event_hash", ""), _negated=True),
                fields=("organization", "event_hash"),
                name="unique_audit_hash_in_org",
            ),
        ),
        migrations.AddField(
            model_name="auditredaction",
            name="approved_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approved_audit_redactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="auditredaction",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="redactions",
                to="core.auditevent",
            ),
        ),
        migrations.AddField(
            model_name="auditredaction",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="audit_redactions",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="auditredaction",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="requested_audit_redactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="auditredaction",
            constraint=models.UniqueConstraint(
                fields=("event",), name="one_redaction_per_audit_event"
            ),
        ),
    ]
