# Generated by Django 6.0.8 on 2026-09-30 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auditredaction_decided_at_auditredaction_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialtype',
            name='applies_to',
            field=models.JSONField(blank=True, default=list, help_text='Personnel categories that must hold this credential. Empty means no category is required to hold it.'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='audience',
            field=models.CharField(choices=[('person', "Attached to one person's file"), ('workforce', 'Company record issued to every worker'), ('management', 'Company record for administrators only')], default='person', max_length=20),
        ),
        migrations.AlterField(
            model_name='persondocument',
            name='person',
            field=models.ForeignKey(blank=True, help_text='Blank for a company-level record such as a handbook or licence.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.person'),
        ),
    ]
