# Generated by Django 6.0.8 on 2026-09-30 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_document_tenant_guard_null_safe'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialtype',
            name='reminder_days_before',
            field=models.JSONField(blank=True, default=list, help_text='Escalating reminder lead times in days before expiry. Empty uses the warning window once.'),
        ),
        migrations.AddField(
            model_name='membershipinvitation',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='core.person'),
        ),
        migrations.AlterField(
            model_name='membershipinvitation',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('hr_compliance', 'HR / Compliance'), ('scheduler', 'Scheduler / Dispatcher'), ('payroll', 'Payroll approver'), ('supervisor', 'Site supervisor'), ('officer', 'Officer'), ('auditor', 'Read-only auditor')], max_length=30),
        ),
    ]
