# Generated by Django 6.0.8 on 2026-09-30 14:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_invitation_provisioning_and_reminder_ladder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='requested', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_shift_claims', to=settings.AUTH_USER_MODEL)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_claims', to='core.person')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_claims', to='core.organization')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='core.shift')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'requested')), fields=('shift', 'officer'), name='one_open_claim_per_shift_officer')],
            },
        ),
    ]
