# Generated by Django 6.0.8 on 2026-09-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_open_post_claims'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='default_bill_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='default_pay_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='required_credentials',
            field=models.ManyToManyField(blank=True, related_name='required_by_clients', to='core.credentialtype'),
        ),
        migrations.AddField(
            model_name='shift',
            name='bill_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Overrides the site and client rate charged for this post.', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='pay_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Overrides the site, client, and officer rate for this post only.', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='default_bill_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='default_pay_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='required_credentials',
            field=models.ManyToManyField(blank=True, related_name='required_by_sites', to='core.credentialtype'),
        ),
    ]
