# Generated by Django 6.0.8 on 2026-09-30 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_post_requirements_and_rates'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorityScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authority_scopes', to='core.branch')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authority_scopes', to='core.client')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authority_scopes', to='core.membership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authority_scopes', to='core.organization')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authority_scopes', to='core.site')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('membership', 'branch'), name='one_branch_authority_per_membership'), models.UniqueConstraint(fields=('membership', 'client'), name='one_client_authority_per_membership'), models.UniqueConstraint(fields=('membership', 'site'), name='one_site_authority_per_membership')],
            },
        ),
    ]
