# Generated by Django 6.0.8 on 2026-09-30 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_availability_and_time_off'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrun',
            name='reopen_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='reopen_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='reopened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='reopened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reopened_payroll_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timepolicy',
            name='allow_reopen',
            field=models.BooleanField(default=False, help_text='Allow an owner or administrator to unlock an approved period so corrections can flow again.'),
        ),
    ]
