# Generated by Django 6.0.8 on 2026-09-30 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_payroll_reopen'),
    ]

    operations = [
        migrations.AddField(
            model_name='persondocument',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='core.persondocument'),
        ),
    ]
