# Generated by Django 6.0.8 on 2026-09-30 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_document_revision_lineage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='timepolicy',
            name='revision',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='TimePolicyOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_geofence', models.BooleanField(blank=True, help_text='Leave unset to inherit the company rule.', null=True)),
                ('rounding_mode', models.CharField(blank=True, choices=[('exact', 'Exact time'), ('nearest', 'Nearest interval'), ('up', 'Always up'), ('down', 'Always down')], max_length=12, null=True)),
                ('rounding_minutes', models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 minutes'), (5, '5 minutes'), (6, '6 minutes'), (10, '10 minutes'), (15, '15 minutes'), (30, '30 minutes')], null=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_time_policies', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='time_policy_overrides', to='core.client')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_policy_overrides', to='core.organization')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='time_policy_overrides', to='core.site')),
            ],
            options={
                'ordering': ['client__name', 'site__name', 'created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('client__isnull', False)), fields=('organization', 'client'), name='one_time_policy_override_per_client'), models.UniqueConstraint(condition=models.Q(('site__isnull', False)), fields=('organization', 'site'), name='one_time_policy_override_per_site')],
            },
        ),
    ]
