# Generated by Django 6.0.8 on 2026-10-01 00:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

# Same database-level tenant integrity as migrations 0012/0019: a model's clean() is not the only
# thing keeping a row on one tenant, because a direct UPDATE can move a foreign key without ever
# loading the object. The two existing shift guards are reinstalled here with the series reference
# added, so a post cannot be pointed at another firm's pattern.
TRIGGERS = {
    "core_shifttemplate_tenant_insert": "CREATE TRIGGER core_shifttemplate_tenant_insert BEFORE INSERT ON core_shifttemplate FOR EACH ROW BEGIN IF (SELECT organization_id FROM core_site WHERE id=NEW.site_id) <> NEW.organization_id OR (NEW.officer_id IS NOT NULL AND (SELECT organization_id FROM core_person WHERE id=NEW.officer_id) <> NEW.organization_id) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='cross-tenant shift template reference'; END IF; END",
    "core_shifttemplate_tenant_update": "CREATE TRIGGER core_shifttemplate_tenant_update BEFORE UPDATE ON core_shifttemplate FOR EACH ROW BEGIN IF (SELECT organization_id FROM core_site WHERE id=NEW.site_id) <> NEW.organization_id OR (NEW.officer_id IS NOT NULL AND (SELECT organization_id FROM core_person WHERE id=NEW.officer_id) <> NEW.organization_id) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='cross-tenant shift template reference'; END IF; END",
    "core_shiftswap_tenant_insert": "CREATE TRIGGER core_shiftswap_tenant_insert BEFORE INSERT ON core_shiftswap FOR EACH ROW BEGIN IF (SELECT organization_id FROM core_shift WHERE id=NEW.shift_id) <> NEW.organization_id OR (SELECT organization_id FROM core_person WHERE id=NEW.requester_id) <> NEW.organization_id OR (SELECT organization_id FROM core_person WHERE id=NEW.replacement_id) <> NEW.organization_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='cross-tenant shift swap reference'; END IF; END",
    "core_shiftswap_tenant_update": "CREATE TRIGGER core_shiftswap_tenant_update BEFORE UPDATE ON core_shiftswap FOR EACH ROW BEGIN IF (SELECT organization_id FROM core_shift WHERE id=NEW.shift_id) <> NEW.organization_id OR (SELECT organization_id FROM core_person WHERE id=NEW.requester_id) <> NEW.organization_id OR (SELECT organization_id FROM core_person WHERE id=NEW.replacement_id) <> NEW.organization_id THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='cross-tenant shift swap reference'; END IF; END",
    "core_shift_tenant_insert": "CREATE TRIGGER core_shift_tenant_insert BEFORE INSERT ON core_shift FOR EACH ROW BEGIN IF (SELECT organization_id FROM core_site WHERE id=NEW.site_id) <> NEW.organization_id OR (NEW.officer_id IS NOT NULL AND (SELECT organization_id FROM core_person WHERE id=NEW.officer_id) <> NEW.organization_id) OR (NEW.template_id IS NOT NULL AND (SELECT organization_id FROM core_shifttemplate WHERE id=NEW.template_id) <> NEW.organization_id) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='cross-tenant shift reference'; END IF; END",
    "core_shift_tenant_update": "CREATE TRIGGER core_shift_tenant_update BEFORE UPDATE ON core_shift FOR EACH ROW BEGIN IF (SELECT organization_id FROM core_site WHERE id=NEW.site_id) <> NEW.organization_id OR (NEW.officer_id IS NOT NULL AND (SELECT organization_id FROM core_person WHERE id=NEW.officer_id) <> NEW.organization_id) OR (NEW.template_id IS NOT NULL AND (SELECT organization_id FROM core_shifttemplate WHERE id=NEW.template_id) <> NEW.organization_id) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='cross-tenant shift reference'; END IF; END",
}

# The shift guards as migration 0012 wrote them, kept so a rollback restores the narrower text.
RESTORED_SHIFT_TRIGGERS = (
    "CREATE TRIGGER core_shift_tenant_insert BEFORE INSERT ON core_shift FOR EACH ROW BEGIN IF (SELECT organization_id FROM core_site WHERE id=NEW.site_id) <> NEW.organization_id OR (NEW.officer_id IS NOT NULL AND (SELECT organization_id FROM core_person WHERE id=NEW.officer_id) <> NEW.organization_id) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='cross-tenant shift reference'; END IF; END",
    "CREATE TRIGGER core_shift_tenant_update BEFORE UPDATE ON core_shift FOR EACH ROW BEGIN IF (SELECT organization_id FROM core_site WHERE id=NEW.site_id) <> NEW.organization_id OR (NEW.officer_id IS NOT NULL AND (SELECT organization_id FROM core_person WHERE id=NEW.officer_id) <> NEW.organization_id) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='cross-tenant shift reference'; END IF; END",
)


def install_tenant_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return
    with schema_editor.connection.cursor() as cursor:
        for name, sql in TRIGGERS.items():
            cursor.execute(f"DROP TRIGGER IF EXISTS {name}")
            cursor.execute(sql)


def remove_tenant_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return
    with schema_editor.connection.cursor() as cursor:
        for name in TRIGGERS:
            cursor.execute(f"DROP TRIGGER IF EXISTS {name}")
        cursor.execute(RESTORED_SHIFT_TRIGGERS[0])
        cursor.execute(RESTORED_SHIFT_TRIGGERS[1])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_evidence_policy_inheritance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftSwap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('offered', 'Waiting for the colleague'), ('agreed', 'Waiting for a manager'), ('approved', 'Approved'), ('declined', 'Declined by the colleague'), ('refused', 'Refused by a manager'), ('withdrawn', 'Withdrawn')], default='offered', max_length=20)),
                ('note', models.CharField(blank=True, help_text='Why the post needs moving. The colleague and the manager both read this.', max_length=255)),
                ('review_note', models.CharField(blank=True, max_length=255)),
                ('agreed_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_shift_swaps', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_swaps', to='core.organization')),
                ('replacement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swaps_received', to='core.person')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swaps_offered', to='core.person')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swaps', to='core.shift')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShiftTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Names the pattern on the schedule, such as “Gate 1 night tour”.', max_length=140)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(help_text='A time earlier than the start means the tour finishes the next morning, which is how a 18:00–06:00 post is stated.')),
                ('weekdays', models.JSONField(blank=True, default=list, help_text='The days of the week this pattern produces.')),
                ('pattern', models.CharField(choices=[('weekly', 'Every week'), ('fortnightly', 'Every other week')], default='weekly', max_length=16)),
                ('series_start', models.DateField(help_text='The week the pattern begins. An every-other-week series counts its phase from this date, so generating a later range does not move the alternating weekends.')),
                ('post_name', models.CharField(blank=True, max_length=140)),
                ('post_orders', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True, help_text='Paused series generate no further posts. Posts already produced stay on the schedule either way.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('officer', models.ForeignKey(blank=True, help_text='Optional. Leave empty to generate each post open, so a qualified officer can ask to take it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_posts', to='core.person')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_templates', to='core.organization')),
                ('required_credentials', models.ManyToManyField(blank=True, related_name='required_for_templates', to='core.credentialtype')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_templates', to='core.site')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='shift',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='core.shifttemplate'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(fields=('template', 'starts_at'), name='one_generated_post_per_occurrence'),
        ),
        migrations.AddConstraint(
            model_name='shiftswap',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ('offered', 'agreed'))), fields=('shift', 'replacement'), name='one_open_swap_per_post_and_colleague'),
        ),
        migrations.RunPython(install_tenant_guards, remove_tenant_guards),
    ]
