# Generated by Django 6.0.8 on 2026-10-01 15:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

# Database-level tenant integrity for the new table, as in migrations 0012/0019/0034: a model's
# clean() is not the only thing keeping a row on one tenant, because a direct UPDATE can move a
# foreign key without ever loading the object. An exchange names two posts and two people, so all
# four are checked — a trade that reached across tenants would move a stranger's assignment.
TRIGGERS = {
    "core_shiftexchange_tenant_insert": "CREATE TRIGGER core_shiftexchange_tenant_insert BEFORE INSERT ON core_shiftexchange FOR EACH ROW BEGIN IF (SELECT organization_id FROM core_person WHERE id=NEW.initiator_id) <> NEW.organization_id OR (SELECT organization_id FROM core_person WHERE id=NEW.partner_id) <> NEW.organization_id OR (SELECT organization_id FROM core_shift WHERE id=NEW.initiator_shift_id) <> NEW.organization_id OR (NEW.partner_shift_id IS NOT NULL AND (SELECT organization_id FROM core_shift WHERE id=NEW.partner_shift_id) <> NEW.organization_id) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='cross-tenant shift exchange reference'; END IF; END",
    "core_shiftexchange_tenant_update": "CREATE TRIGGER core_shiftexchange_tenant_update BEFORE UPDATE ON core_shiftexchange FOR EACH ROW BEGIN IF (SELECT organization_id FROM core_person WHERE id=NEW.initiator_id) <> NEW.organization_id OR (SELECT organization_id FROM core_person WHERE id=NEW.partner_id) <> NEW.organization_id OR (SELECT organization_id FROM core_shift WHERE id=NEW.initiator_shift_id) <> NEW.organization_id OR (NEW.partner_shift_id IS NOT NULL AND (SELECT organization_id FROM core_shift WHERE id=NEW.partner_shift_id) <> NEW.organization_id) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='cross-tenant shift exchange reference'; END IF; END",
}


def install_tenant_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return
    with schema_editor.connection.cursor() as cursor:
        for name, sql in TRIGGERS.items():
            cursor.execute(f"DROP TRIGGER IF EXISTS {name}")
            cursor.execute(sql)


def remove_tenant_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return
    with schema_editor.connection.cursor() as cursor:
        for name in TRIGGERS:
            cursor.execute(f"DROP TRIGGER IF EXISTS {name}")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_recurring_series_and_shift_swaps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftswap',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_shift_swaps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shiftswap',
            name='raised_by',
            field=models.CharField(choices=[('officer', 'The officer standing the post'), ('manager', "A manager, on the officer's behalf")], default='officer', max_length=12),
        ),
        migrations.AddField(
            model_name='shifttemplate',
            name='alias',
            field=models.CharField(blank=True, help_text='What the firm calls it — “2s and 3s”, “Panama”, “the nights block”. Names are not standardised, so this is text, not a choice.', max_length=80),
        ),
        migrations.AddField(
            model_name='shifttemplate',
            name='auto_generate_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Set to keep this series filled unattended that many days ahead, never past the end date. Leave empty to generate only from the screen.', null=True),
        ),
        migrations.AddField(
            model_name='shifttemplate',
            name='auto_publish',
            field=models.BooleanField(default=False, help_text='Only an unattended run reads this: drafts hold the coverage, published announces it.'),
        ),
        migrations.AddField(
            model_name='shifttemplate',
            name='cycle_days',
            field=models.PositiveSmallIntegerField(blank=True, help_text='How many days the rotation takes to repeat. Only used by a rotating cycle.', null=True),
        ),
        migrations.AddField(
            model_name='shifttemplate',
            name='cycle_work_days',
            field=models.JSONField(blank=True, default=list, help_text='Which days of the cycle are worked, counted from the first day of the series. Empty days are off.'),
        ),
        migrations.AddField(
            model_name='shifttemplate',
            name='series_end',
            field=models.DateField(blank=True, help_text='Leave empty for an open-ended series. When set, the pattern produces no post after this date and generation can be run up to it in one action.', null=True),
        ),
        migrations.AlterField(
            model_name='shiftswap',
            name='status',
            field=models.CharField(choices=[('offered', 'Waiting for the colleague'), ('agreed', 'Waiting for a manager'), ('approved', 'Approved'), ('declined', 'Declined by the colleague'), ('refused', 'Refused by a manager'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired before an answer')], default='offered', max_length=20),
        ),
        migrations.AlterField(
            model_name='shifttemplate',
            name='pattern',
            field=models.CharField(choices=[('weekly', 'Every week'), ('fortnightly', 'Every other week'), ('cycle', 'A rotating cycle of days')], default='weekly', max_length=16),
        ),
        migrations.CreateModel(
            name='ShiftExchange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('proposed', 'Waiting for the colleague to choose a post'), ('agreed', 'Waiting for a manager'), ('approved', 'Approved'), ('declined', 'Declined by the colleague'), ('refused', 'Refused by a manager'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired before an answer')], default='proposed', max_length=20)),
                ('raised_by', models.CharField(choices=[('officer', 'One of the two officers'), ('manager', 'A manager, on their behalf')], default='officer', max_length=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('review_note', models.CharField(blank=True, max_length=255)),
                ('agreed_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_shift_exchanges', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_shift_exchanges', to=settings.AUTH_USER_MODEL)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges_proposed', to='core.person')),
                ('initiator_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges_initiated', to='core.shift')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_exchanges', to='core.organization')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges_invited', to='core.person')),
                ('partner_shift', models.ForeignKey(blank=True, help_text='Chosen by the colleague being asked to trade, not by the officer who proposed it.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exchanges_partnered', to='core.shift')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ('proposed', 'agreed'))), fields=('initiator', 'initiator_shift'), name='one_open_exchange_per_post')],
            },
        ),
        migrations.RunPython(install_tenant_guards, remove_tenant_guards),
    ]
