# Generated by Django 6.0.8 on 2026-10-01 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# This table is what a wage claim gets answered with, so it carries the same database-level
# immutability as the audit chain (migration 0018): a history that can be edited to match the
# present rule text is not evidence of anything. Writes only ever INSERT.
TRIGGERS = {
    "core_rulerevision_no_update": "CREATE TRIGGER core_rulerevision_no_update BEFORE UPDATE ON core_rulerevision FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='rule revisions are immutable'",
    "core_rulerevision_no_delete": "CREATE TRIGGER core_rulerevision_no_delete BEFORE DELETE ON core_rulerevision FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='rule revisions are immutable'",
}


def install_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return
    with schema_editor.connection.cursor() as cursor:
        for name, sql in TRIGGERS.items():
            cursor.execute(f"DROP TRIGGER IF EXISTS {name}")
            cursor.execute(sql)


def remove_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return
    with schema_editor.connection.cursor() as cursor:
        for name in TRIGGERS:
            cursor.execute(f"DROP TRIGGER IF EXISTS {name}")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_shift_exchanges_and_rotations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialtype',
            name='revision',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='RuleRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('clock_policy', 'Company clock policy'), ('clock_rule', 'Contract or site clock rule'), ('credential_rule', 'Credential requirement')], max_length=24)),
                ('rule_id', models.CharField(max_length=40)),
                ('revision', models.PositiveIntegerField()),
                ('values', models.JSONField(blank=True, default=dict)),
                ('changed', models.JSONField(blank=True, default=dict)),
                ('label', models.CharField(blank=True, help_text='What the rule was called at the time, so a removed rule still reads as itself.', max_length=200)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_revisions', to='core.organization')),
                ('saved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_rule_revisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['kind', 'rule_id', 'revision'],
                'indexes': [models.Index(fields=['organization', 'kind', 'rule_id'], name='core_rulere_organiz_79e8f1_idx')],
                'constraints': [models.UniqueConstraint(fields=('kind', 'rule_id', 'revision'), name='one_row_per_rule_version')],
            },
        ),
        migrations.RunPython(install_guards, remove_guards),
    ]
