# Generated by Django 6.0.8 on 2026-10-01 23:30

import django.db.models.deletion
from django.db import migrations, models

# Hand-written cross-tenant guards, as in migrations 0012/0019/0025/0034/0035: a model's clean()
# is not the only thing keeping a row on one tenant, because a direct UPDATE can move a foreign key
# without ever loading the object. Each of these three tables now points at a pay code, so each
# guard is reinstalled with the new clause added to the ones already there — and `core_client` gets
# its first guard, having had no tenant-owned foreign key before this column existed.
GUARDS = {
    "core_client_tenant_insert": "CREATE TRIGGER core_client_tenant_insert BEFORE INSERT ON core_client FOR EACH ROW BEGIN IF (NEW.default_pay_code_id IS NOT NULL AND (SELECT organization_id FROM core_paycode WHERE id=NEW.default_pay_code_id) <> NEW.organization_id) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='cross-tenant client reference'; END IF; END",
    "core_client_tenant_update": "CREATE TRIGGER core_client_tenant_update BEFORE UPDATE ON core_client FOR EACH ROW BEGIN IF (NEW.default_pay_code_id IS NOT NULL AND (SELECT organization_id FROM core_paycode WHERE id=NEW.default_pay_code_id) <> NEW.organization_id) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='cross-tenant client reference'; END IF; END",
    "core_site_tenant_insert": "CREATE TRIGGER core_site_tenant_insert BEFORE INSERT ON core_site FOR EACH ROW BEGIN IF (SELECT organization_id FROM core_client WHERE id=NEW.client_id) <> NEW.organization_id OR (NEW.branch_id IS NOT NULL AND (SELECT organization_id FROM core_branch WHERE id=NEW.branch_id) <> NEW.organization_id) OR (NEW.default_pay_code_id IS NOT NULL AND (SELECT organization_id FROM core_paycode WHERE id=NEW.default_pay_code_id) <> NEW.organization_id) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='cross-tenant site reference'; END IF; END",
    "core_site_tenant_update": "CREATE TRIGGER core_site_tenant_update BEFORE UPDATE ON core_site FOR EACH ROW BEGIN IF (SELECT organization_id FROM core_client WHERE id=NEW.client_id) <> NEW.organization_id OR (NEW.branch_id IS NOT NULL AND (SELECT organization_id FROM core_branch WHERE id=NEW.branch_id) <> NEW.organization_id) OR (NEW.default_pay_code_id IS NOT NULL AND (SELECT organization_id FROM core_paycode WHERE id=NEW.default_pay_code_id) <> NEW.organization_id) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='cross-tenant site reference'; END IF; END",
    "core_shift_tenant_insert": "CREATE TRIGGER core_shift_tenant_insert BEFORE INSERT ON core_shift FOR EACH ROW BEGIN IF (SELECT organization_id FROM core_site WHERE id=NEW.site_id) <> NEW.organization_id OR (NEW.officer_id IS NOT NULL AND (SELECT organization_id FROM core_person WHERE id=NEW.officer_id) <> NEW.organization_id) OR (NEW.template_id IS NOT NULL AND (SELECT organization_id FROM core_shifttemplate WHERE id=NEW.template_id) <> NEW.organization_id) OR (NEW.pay_code_id IS NOT NULL AND (SELECT organization_id FROM core_paycode WHERE id=NEW.pay_code_id) <> NEW.organization_id) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='cross-tenant shift reference'; END IF; END",
    "core_shift_tenant_update": "CREATE TRIGGER core_shift_tenant_update BEFORE UPDATE ON core_shift FOR EACH ROW BEGIN IF (SELECT organization_id FROM core_site WHERE id=NEW.site_id) <> NEW.organization_id OR (NEW.officer_id IS NOT NULL AND (SELECT organization_id FROM core_person WHERE id=NEW.officer_id) <> NEW.organization_id) OR (NEW.template_id IS NOT NULL AND (SELECT organization_id FROM core_shifttemplate WHERE id=NEW.template_id) <> NEW.organization_id) OR (NEW.pay_code_id IS NOT NULL AND (SELECT organization_id FROM core_paycode WHERE id=NEW.pay_code_id) <> NEW.organization_id) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='cross-tenant shift reference'; END IF; END",
}

# The site and shift guards as they stood before this column, restored on rollback so a downgrade
# does not leave a clause behind referring to a column that will be gone.
RESTORED = (
    "CREATE TRIGGER core_site_tenant_insert BEFORE INSERT ON core_site FOR EACH ROW BEGIN IF (SELECT organization_id FROM core_client WHERE id=NEW.client_id) <> NEW.organization_id OR (NEW.branch_id IS NOT NULL AND (SELECT organization_id FROM core_branch WHERE id=NEW.branch_id) <> NEW.organization_id) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='cross-tenant site reference'; END IF; END",
    "CREATE TRIGGER core_site_tenant_update BEFORE UPDATE ON core_site FOR EACH ROW BEGIN IF (SELECT organization_id FROM core_client WHERE id=NEW.client_id) <> NEW.organization_id OR (NEW.branch_id IS NOT NULL AND (SELECT organization_id FROM core_branch WHERE id=NEW.branch_id) <> NEW.organization_id) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='cross-tenant site reference'; END IF; END",
    "CREATE TRIGGER core_shift_tenant_insert BEFORE INSERT ON core_shift FOR EACH ROW BEGIN IF (SELECT organization_id FROM core_site WHERE id=NEW.site_id) <> NEW.organization_id OR (NEW.officer_id IS NOT NULL AND (SELECT organization_id FROM core_person WHERE id=NEW.officer_id) <> NEW.organization_id) OR (NEW.template_id IS NOT NULL AND (SELECT organization_id FROM core_shifttemplate WHERE id=NEW.template_id) <> NEW.organization_id) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='cross-tenant shift reference'; END IF; END",
    "CREATE TRIGGER core_shift_tenant_update BEFORE UPDATE ON core_shift FOR EACH ROW BEGIN IF (SELECT organization_id FROM core_site WHERE id=NEW.site_id) <> NEW.organization_id OR (NEW.officer_id IS NOT NULL AND (SELECT organization_id FROM core_person WHERE id=NEW.officer_id) <> NEW.organization_id) OR (NEW.template_id IS NOT NULL AND (SELECT organization_id FROM core_shifttemplate WHERE id=NEW.template_id) <> NEW.organization_id) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='cross-tenant shift reference'; END IF; END",
)


def install_tenant_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return
    with schema_editor.connection.cursor() as cursor:
        for name, sql in GUARDS.items():
            cursor.execute(f"DROP TRIGGER IF EXISTS {name}")
            cursor.execute(sql)


def remove_tenant_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return
    with schema_editor.connection.cursor() as cursor:
        for name in GUARDS:
            cursor.execute(f"DROP TRIGGER IF EXISTS {name}")
        for sql in RESTORED:
            cursor.execute(sql)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_rule_revision_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('code', models.SlugField(help_text="The literal string the customer's payroll system expects.", max_length=60)),
                ('cost_centre', models.CharField(blank=True, help_text='Optional account or department the hours are charged to.', max_length=60)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_codes', to='core.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='default_pay_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_by_clients', to='core.paycode'),
        ),
        migrations.AddField(
            model_name='shift',
            name='pay_code',
            field=models.ForeignKey(blank=True, help_text='Overrides the site and contract code for this post only.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='core.paycode'),
        ),
        migrations.AddField(
            model_name='site',
            name='default_pay_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_by_sites', to='core.paycode'),
        ),
        migrations.AddConstraint(
            model_name='paycode',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_pay_code_in_org'),
        ),
        migrations.RunPython(install_tenant_guards, remove_tenant_guards),
    ]
