# Generated by Django 6.0.8 on 2026-10-02 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_pay_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='sensitivity',
            field=models.CharField(choices=[('standard', 'Personnel file'), ('restricted', 'Restricted'), ('sealed', 'Sealed')], default='standard', help_text='Who may open a record of this type, in addition to its audience.', max_length=20),
        ),
    ]
