# Generated by Django 6.0.8 on 2026-10-02 00:44

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


# Database-level tenant integrity for the new table, as in migrations 0012/0019/0034/0035: a rule
# names the record type that proves it, and a duty pointing at another company's record type would
# report that company's filings as this one's compliance. `clean()` cannot catch that through a
# direct UPDATE, which never loads the object.
TRIGGERS = {
    "core_compliancerule_tenant_insert": "CREATE TRIGGER core_compliancerule_tenant_insert BEFORE INSERT ON core_compliancerule FOR EACH ROW BEGIN IF (NEW.document_type_id IS NOT NULL AND (SELECT organization_id FROM core_documenttype WHERE id=NEW.document_type_id) <> NEW.organization_id) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='cross-tenant compliance rule reference'; END IF; END",
    "core_compliancerule_tenant_update": "CREATE TRIGGER core_compliancerule_tenant_update BEFORE UPDATE ON core_compliancerule FOR EACH ROW BEGIN IF (NEW.document_type_id IS NOT NULL AND (SELECT organization_id FROM core_documenttype WHERE id=NEW.document_type_id) <> NEW.organization_id) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='cross-tenant compliance rule reference'; END IF; END",
}


def install_tenant_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return
    with schema_editor.connection.cursor() as cursor:
        for name, sql in TRIGGERS.items():
            cursor.execute(f"DROP TRIGGER IF EXISTS {name}")
            cursor.execute(sql)


def remove_tenant_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return
    with schema_editor.connection.cursor() as cursor:
        for name in TRIGGERS:
            cursor.execute(f"DROP TRIGGER IF EXISTS {name}")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_record_sensitivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulerevision',
            name='kind',
            field=models.CharField(choices=[('clock_policy', 'Company clock policy'), ('clock_rule', 'Contract or site clock rule'), ('credential_rule', 'Credential requirement'), ('compliance_rule', 'Compliance duty')], max_length=24),
        ),
        migrations.CreateModel(
            name='ComplianceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('code', models.SlugField(max_length=60)),
                ('evidence', models.CharField(choices=[('document', 'A filed record of the named type'), ('posting', 'A notice posted where the work is performed'), ('training_hours', 'Training hours on file'), ('credential', 'A numbered credential (entered as a requirement)')], default='document', max_length=20)),
                ('applies_to_subject', models.CharField(choices=[('organization', 'The company'), ('people', 'Officers in the listed categories'), ('sites', 'Each site the company operates')], default='people', max_length=20)),
                ('applies_to', models.JSONField(blank=True, default=list, help_text='Personnel categories that must satisfy this rule. Only consulted when the subject is officers.')),
                ('required_hours', models.PositiveIntegerField(blank=True, help_text='For a training-hours rule: how many are required.', null=True)),
                ('warning_days', models.PositiveIntegerField(default=60, help_text='Renewal lead time for evidence that itself expires.')),
                ('reminder_days_before', models.JSONField(blank=True, default=list, help_text='Escalating reminder lead times in days. Empty uses the warning window once.')),
                ('jurisdiction', models.CharField(default='Texas', max_length=80)),
                ('authority_url', models.URLField(blank=True)),
                ('authority_reference', models.CharField(blank=True, max_length=180)),
                ('interpretation', models.TextField(blank=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_compliance_rules', to=settings.AUTH_USER_MODEL)),
                ('document_type', models.ForeignKey(blank=True, help_text='For a filed-record rule: which record type proves it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rules_requiring_it', to='core.documenttype')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_rules', to='core.organization')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'code'), name='unique_compliance_rule_code_in_org')],
            },
            bases=(core.models.RuleVocabulary, models.Model),
        ),
        migrations.RunPython(install_tenant_guards, remove_tenant_guards),
    ]
