# Generated by Django 6.0.8 on 2026-10-02 02:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


# Database-level tenant integrity for the new table, as in migrations 0012/0019/0034/0035/0039: a
# saved figure names the branch or contract it describes, and a row borrowed from another tenant
# would publish one company's compliance rate inside another company's history. `clean()` does not
# see a direct UPDATE, which never loads the object.
TRIGGERS = {
    "core_reportsnapshot_tenant_insert": "CREATE TRIGGER core_reportsnapshot_tenant_insert BEFORE INSERT ON core_reportsnapshot FOR EACH ROW BEGIN IF (NEW.branch_id IS NOT NULL AND (SELECT organization_id FROM core_branch WHERE id=NEW.branch_id) <> NEW.organization_id) OR (NEW.client_id IS NOT NULL AND (SELECT organization_id FROM core_client WHERE id=NEW.client_id) <> NEW.organization_id) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='cross-tenant report snapshot reference'; END IF; END",
    "core_reportsnapshot_tenant_update": "CREATE TRIGGER core_reportsnapshot_tenant_update BEFORE UPDATE ON core_reportsnapshot FOR EACH ROW BEGIN IF (NEW.branch_id IS NOT NULL AND (SELECT organization_id FROM core_branch WHERE id=NEW.branch_id) <> NEW.organization_id) OR (NEW.client_id IS NOT NULL AND (SELECT organization_id FROM core_client WHERE id=NEW.client_id) <> NEW.organization_id) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='cross-tenant report snapshot reference'; END IF; END",
}


def install_tenant_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return
    with schema_editor.connection.cursor() as cursor:
        for name, sql in TRIGGERS.items():
            cursor.execute(f"DROP TRIGGER IF EXISTS {name}")
            cursor.execute(sql)


def remove_tenant_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return
    with schema_editor.connection.cursor() as cursor:
        for name in TRIGGERS:
            cursor.execute(f"DROP TRIGGER IF EXISTS {name}")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_compliance_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_date', models.DateField()),
                ('metric', models.CharField(choices=[('compliance', 'Compliance rate'), ('coverage', 'Published posts staffed and eligible'), ('tour', 'Tours with complete time evidence')], max_length=20)),
                ('subject_key', models.CharField(help_text="'company', 'branch:<id>', or 'client:<id>'.", max_length=72)),
                ('total', models.PositiveIntegerField(default=0)),
                ('satisfied', models.PositiveIntegerField(default=0)),
                ('attention', models.PositiveIntegerField(default=0)),
                ('rate', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('basis', models.JSONField(default=dict, help_text='Window, kinds counted, exclusions, and the reader basis the figure was taken on.')),
                ('exceptions', models.JSONField(default=list, help_text="The items that made up 'needs action', so the number can be read back.")),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_snapshots', to='core.branch')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_snapshots', to='core.client')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_snapshots', to='core.organization')),
            ],
            options={
                'ordering': ['-period_date', 'metric', 'subject_key'],
                'indexes': [models.Index(fields=['organization', 'metric', 'subject_key', 'period_date'], name='core_report_organiz_0db40a_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'subject_key', 'metric', 'period_date'), name='one_report_snapshot_per_subject_metric_day')],
            },
        ),
        migrations.RunPython(install_tenant_guards, remove_tenant_guards),
    ]
