# Generated by Django 6.0.8 on 2026-10-02 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_report_snapshots'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositionrequest',
            name='restore_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dispositionrequest',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispositionrequest',
            name='restored_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='restored_dispositions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dispositionrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending approval'), ('executed', 'Executed'), ('cancelled', 'Cancelled'), ('restored', 'Reversed — record restored')], default='pending', max_length=20),
        ),
    ]
