# Generated by Django 6.0.8 on 2026-10-03 19:35

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


# Database-level tenant integrity for the three new tables, in the shape of migrations
# 0012/0019/0034/0035/0039/0040. Each row names another tenant-scoped table — a checklist step points
# at the record type or requirement it expects, a task points at the officer and the step, a
# registry check points at the credential — and a row borrowed across tenants would put one company's
# new-hire obligations, or its licence verification trail, inside another company's file. `clean()`
# does not see a direct UPDATE, which never loads the object.
#
# The conditional reference is written out per column rather than as one expression because MySQL
# evaluates `(SELECT ... WHERE id=NEW.x) <> NEW.organization_id` as NULL when the child row is
# absent, and NULL in an OR chain makes the whole guard quietly pass on a non-NULL column.
TRIGGERS = {
    "core_onboardingitem_tenant_insert": (
        "CREATE TRIGGER core_onboardingitem_tenant_insert BEFORE INSERT ON core_onboardingitem FOR EACH ROW BEGIN "
        "IF (NEW.document_type_id IS NOT NULL AND (SELECT COUNT(*) FROM core_documenttype d WHERE d.id=NEW.document_type_id AND d.organization_id=NEW.organization_id)=0) "
        "OR (NEW.credential_type_id IS NOT NULL AND (SELECT COUNT(*) FROM core_credentialtype c WHERE c.id=NEW.credential_type_id AND c.organization_id=NEW.organization_id)=0) "
        "THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='cross-tenant onboarding item reference'; END IF; END"
    ),
    "core_onboardingitem_tenant_update": (
        "CREATE TRIGGER core_onboardingitem_tenant_update BEFORE UPDATE ON core_onboardingitem FOR EACH ROW BEGIN "
        "IF (NEW.document_type_id IS NOT NULL AND (SELECT COUNT(*) FROM core_documenttype d WHERE d.id=NEW.document_type_id AND d.organization_id=NEW.organization_id)=0) "
        "OR (NEW.credential_type_id IS NOT NULL AND (SELECT COUNT(*) FROM core_credentialtype c WHERE c.id=NEW.credential_type_id AND c.organization_id=NEW.organization_id)=0) "
        "THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='cross-tenant onboarding item reference'; END IF; END"
    ),
    "core_onboardingtask_tenant_insert": (
        "CREATE TRIGGER core_onboardingtask_tenant_insert BEFORE INSERT ON core_onboardingtask FOR EACH ROW BEGIN "
        "IF (SELECT COUNT(*) FROM core_person p WHERE p.id=NEW.person_id AND p.organization_id=NEW.organization_id)=0 "
        "OR (SELECT COUNT(*) FROM core_onboardingitem i WHERE i.id=NEW.item_id AND i.organization_id=NEW.organization_id)=0 "
        "THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='cross-tenant onboarding task reference'; END IF; END"
    ),
    "core_onboardingtask_tenant_update": (
        "CREATE TRIGGER core_onboardingtask_tenant_update BEFORE UPDATE ON core_onboardingtask FOR EACH ROW BEGIN "
        "IF (SELECT COUNT(*) FROM core_person p WHERE p.id=NEW.person_id AND p.organization_id=NEW.organization_id)=0 "
        "OR (SELECT COUNT(*) FROM core_onboardingitem i WHERE i.id=NEW.item_id AND i.organization_id=NEW.organization_id)=0 "
        "THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='cross-tenant onboarding task reference'; END IF; END"
    ),
    "core_credentialregistrycheck_tenant_insert": (
        "CREATE TRIGGER core_credentialregistrycheck_tenant_insert BEFORE INSERT ON core_credentialregistrycheck FOR EACH ROW BEGIN "
        "IF (SELECT COUNT(*) FROM core_credential cr WHERE cr.id=NEW.credential_id AND cr.organization_id=NEW.organization_id)=0 "
        "THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='cross-tenant registry check reference'; END IF; END"
    ),
    "core_credentialregistrycheck_tenant_update": (
        "CREATE TRIGGER core_credentialregistrycheck_tenant_update BEFORE UPDATE ON core_credentialregistrycheck FOR EACH ROW BEGIN "
        "IF (SELECT COUNT(*) FROM core_credential cr WHERE cr.id=NEW.credential_id AND cr.organization_id=NEW.organization_id)=0 "
        "THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='cross-tenant registry check reference'; END IF; END"
    ),
}


def install_tenant_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return
    with schema_editor.connection.cursor() as cursor:
        for name, sql in TRIGGERS.items():
            cursor.execute(f"DROP TRIGGER IF EXISTS {name}")
            cursor.execute(sql)


def remove_tenant_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return
    with schema_editor.connection.cursor() as cursor:
        for name in TRIGGERS:
            cursor.execute(f"DROP TRIGGER IF EXISTS {name}")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_record_recovery_and_export'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialtype',
            name='registry_check_within_days',
            field=models.PositiveIntegerField(blank=True, help_text='How often to re-check this credential against the DPS registry. Leave empty when no periodic check is owed.', null=True),
        ),
        migrations.CreateModel(
            name='OnboardingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('code', models.SlugField(max_length=60)),
                ('kind', models.CharField(choices=[('task', 'A step someone marks done'), ('document', 'A record filed in the personnel file'), ('credential', 'A numbered registration or commission on file')], default='task', max_length=20)),
                ('owner', models.CharField(choices=[('person', 'The new hire'), ('staff', 'Somebody in the office')], default='person', max_length=10)),
                ('instructions', models.TextField(blank=True)),
                ('due_within_days', models.PositiveIntegerField(default=7, help_text='Calendar days after the hire date this step is owed by.')),
                ('applies_to', models.JSONField(blank=True, default=list, help_text='Personnel categories that must do this step. Empty means every new hire.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credential_type', models.ForeignKey(blank=True, help_text='For a credential step: which requirement must be on file.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='onboarding_items', to='core.credentialtype')),
                ('document_type', models.ForeignKey(blank=True, help_text='For a record step: which type must be on file.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_items', to='core.documenttype')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_items', to='core.organization')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
            bases=(core.models.AppliesToCategories, models.Model),
        ),
        migrations.CreateModel(
            name='OnboardingTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('due_on', models.DateField(blank=True, help_text="Hire date plus the step's lead time when this was issued. Empty means no hire date was recorded yet.", null=True)),
                ('status', models.CharField(choices=[('open', 'Outstanding'), ('done', 'Complete'), ('waived', 'Not required for this person')], default='open', max_length=10)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, help_text='Why this was waived, or what was accepted as proof.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_decisions', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='core.onboardingitem')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_tasks', to='core.organization')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_tasks', to='core.person')),
            ],
            options={
                'ordering': ['item__order', 'item__name'],
            },
        ),
        migrations.CreateModel(
            name='CredentialRegistryCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checked_on', models.DateField()),
                ('result', models.CharField(choices=[('valid', 'Registry shows it valid'), ('expired', 'Registry shows it expired'), ('not_found', 'No registry record found'), ('attention', 'Registry disagrees with the record on file')], default='valid', max_length=20)),
                ('registry_reference', models.CharField(blank=True, help_text='What the registry itself displayed, so the next checker can compare.', max_length=120)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credential_registry_checks', to=settings.AUTH_USER_MODEL)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registry_checks', to='core.credential')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credential_registry_checks', to='core.organization')),
            ],
            options={
                'ordering': ['-checked_on', '-created_at'],
                'indexes': [models.Index(fields=['credential', 'checked_on'], name='core_registrycheck_credential')],
            },
        ),
        migrations.AddConstraint(
            model_name='onboardingitem',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_onboarding_item_code_in_org'),
        ),
        migrations.AddIndex(
            model_name='onboardingtask',
            index=models.Index(fields=['organization', 'person', 'status'], name='core_onboardingtask_state'),
        ),
        migrations.AddConstraint(
            model_name='onboardingtask',
            constraint=models.UniqueConstraint(fields=('person', 'item'), name='one_onboarding_task_per_person_item'),
        ),
        migrations.RunPython(install_tenant_guards, remove_tenant_guards),
    ]
