# Generated by Django 6.0.8 on 2026-10-03 20:41

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


# Database-level tenant integrity for the designation table, as in 0012/0019/0034/0035/0039/0040/0042.
# A designation names a post and a pay category, and a row pointing at another tenant's either
# would price one company's hours with another company's multiplier. `PayCategory` needs no guard:
# it references nothing but its own organization. COUNT() rather than a bare subquery so a missing
# child row is a refusal instead of a NULL that slips through the OR chain (0025's lesson).
TRIGGERS = {
    "core_shifthourdesignation_tenant_insert": (
        "CREATE TRIGGER core_shifthourdesignation_tenant_insert BEFORE INSERT ON core_shifthourdesignation FOR EACH ROW BEGIN "
        "IF (SELECT COUNT(*) FROM core_shift s WHERE s.id=NEW.shift_id AND s.organization_id=NEW.organization_id)=0 "
        "OR (SELECT COUNT(*) FROM core_paycategory c WHERE c.id=NEW.category_id AND c.organization_id=NEW.organization_id)=0 "
        "THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='cross-tenant hour designation reference'; END IF; END"
    ),
    "core_shifthourdesignation_tenant_update": (
        "CREATE TRIGGER core_shifthourdesignation_tenant_update BEFORE UPDATE ON core_shifthourdesignation FOR EACH ROW BEGIN "
        "IF (SELECT COUNT(*) FROM core_shift s WHERE s.id=NEW.shift_id AND s.organization_id=NEW.organization_id)=0 "
        "OR (SELECT COUNT(*) FROM core_paycategory c WHERE c.id=NEW.category_id AND c.organization_id=NEW.organization_id)=0 "
        "THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='cross-tenant hour designation reference'; END IF; END"
    ),
}


def install_tenant_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return
    with schema_editor.connection.cursor() as cursor:
        for name, sql in TRIGGERS.items():
            cursor.execute(f"DROP TRIGGER IF EXISTS {name}")
            cursor.execute(sql)


def remove_tenant_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return
    with schema_editor.connection.cursor() as cursor:
        for name in TRIGGERS:
            cursor.execute(f"DROP TRIGGER IF EXISTS {name}")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_onboarding_and_registry_checks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='timepolicy',
            name='overtime_premium',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.50'), help_text='Rate applied to overtime hours, as a multiple of the pay rate. A contract that pays double time over its own threshold sets 2.00.', max_digits=4),
        ),
        migrations.CreateModel(
            name='PayCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('break', 'Break'), ('holiday', 'Holiday'), ('training', 'Training'), ('travel', 'Travel'), ('double_time', 'Double time')], max_length=20)),
                ('name', models.CharField(max_length=140)),
                ('paid', models.BooleanField(default=True, help_text="Unpaid hours are deducted from the tour, which also lowers the week's total.")),
                ('multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text="Rate as a multiple of the officer's pay rate.", max_digits=4)),
                ('counts_toward_overtime', models.BooleanField(default=True, help_text='Whether these hours count toward the weekly threshold that turns time into overtime.')),
                ('interpretation', models.TextField(blank=True, help_text='Why this firm treats the kind this way, in the words somebody can point at later.')),
                ('revision', models.PositiveIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_categories', to='core.organization')),
            ],
            options={
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ShiftHourDesignation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='designations', to='core.paycategory')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hour_designations', to='core.organization')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hour_designations', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hour_designations', to='core.shift')),
            ],
            options={
                'ordering': ['shift__starts_at', 'category__kind'],
            },
        ),
        migrations.AddConstraint(
            model_name='paycategory',
            constraint=models.UniqueConstraint(fields=('organization', 'kind'), name='one_pay_category_per_kind_in_org'),
        ),
        migrations.AddConstraint(
            model_name='shifthourdesignation',
            constraint=models.UniqueConstraint(fields=('shift', 'category'), name='one_designation_per_shift_category'),
        ),
        migrations.RunPython(install_tenant_guards, remove_tenant_guards),
    ]
