# Generated by Django 6.0.8 on 2026-10-03 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_pay_categories_and_overtime_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paycategory',
            name='kind',
            field=models.CharField(choices=[('break', 'Break'), ('holiday', 'Holiday'), ('training', 'Training'), ('travel', 'Travel'), ('double_time', 'Double time'), ('differential', 'Differential')], max_length=20),
        ),
        migrations.AlterField(
            model_name='rulerevision',
            name='kind',
            field=models.CharField(choices=[('clock_policy', 'Company clock policy'), ('clock_rule', 'Contract or site clock rule'), ('credential_rule', 'Credential requirement'), ('compliance_rule', 'Compliance duty'), ('pay_category', 'Pay category')], max_length=24),
        ),
    ]
