# Generated by Django 6.0.8 on 2026-10-03 22:05
#
# SCH-3: hold-overs and split tours. The tenant guards below are part of this migration, not an
# afterthought — a hold-over names another company's post and another company's officer, and both
# would put one firm's overrun on another firm's timecard.

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

# core_shift already carries a BEFORE INSERT and a BEFORE UPDATE tenant guard (0012, widened by 0034
# for template_id and by 0037 for pay_code_id). MySQL permits only one trigger per timing and event
# per table, so giving a post a `relief_for` means replacing that chain with a longer one exactly the
# way those two migrations did. The existing clauses are copied verbatim rather than restyled —
# rewriting a guard that CI already exercises would mix an unrelated change into this one.
#
# The new clause is written as COUNT() rather than a bare subquery, per 0025's lesson: a subselect on
# a row that does not exist yields NULL, `NULL <> NEW.organization_id` is NULL, and an OR chain
# steps over it. COUNT makes a missing parent a refusal instead of a pass.
#
# And it has to be guarded by `IS NOT NULL`, which is the part that only a real server catches: on an
# ordinary post `s.id = NULL` matches no rows, so COUNT() is 0 and an unguarded clause refuses *every*
# shift insert. The sqlite leg cannot see that at all — the trigger is skipped — so this is stated
# here rather than left for the next person to rediscover on a production migration.
SHIFT_GUARDS = {
    "core_shift_tenant_insert": (
        "CREATE TRIGGER core_shift_tenant_insert BEFORE INSERT ON core_shift FOR EACH ROW BEGIN "
        "IF (SELECT organization_id FROM core_site WHERE id=NEW.site_id) <> NEW.organization_id "
        "OR (NEW.officer_id IS NOT NULL AND (SELECT organization_id FROM core_person WHERE id=NEW.officer_id) <> NEW.organization_id) "
        "OR (NEW.template_id IS NOT NULL AND (SELECT organization_id FROM core_shifttemplate WHERE id=NEW.template_id) <> NEW.organization_id) "
        "OR (NEW.pay_code_id IS NOT NULL AND (SELECT organization_id FROM core_paycode WHERE id=NEW.pay_code_id) <> NEW.organization_id) "
        "OR (NEW.relief_for_id IS NOT NULL AND (SELECT COUNT(*) FROM core_shift s WHERE s.id=NEW.relief_for_id AND s.organization_id=NEW.organization_id)=0) "
        "THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='cross-tenant shift reference'; END IF; END"
    ),
    "core_shift_tenant_update": (
        "CREATE TRIGGER core_shift_tenant_update BEFORE UPDATE ON core_shift FOR EACH ROW BEGIN "
        "IF (SELECT organization_id FROM core_site WHERE id=NEW.site_id) <> NEW.organization_id "
        "OR (NEW.officer_id IS NOT NULL AND (SELECT organization_id FROM core_person WHERE id=NEW.officer_id) <> NEW.organization_id) "
        "OR (NEW.template_id IS NOT NULL AND (SELECT organization_id FROM core_shifttemplate WHERE id=NEW.template_id) <> NEW.organization_id) "
        "OR (NEW.pay_code_id IS NOT NULL AND (SELECT organization_id FROM core_paycode WHERE id=NEW.pay_code_id) <> NEW.organization_id) "
        "OR (NEW.relief_for_id IS NOT NULL AND (SELECT COUNT(*) FROM core_shift s WHERE s.id=NEW.relief_for_id AND s.organization_id=NEW.organization_id)=0) "
        "THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='cross-tenant shift reference'; END IF; END"
    ),
}

# The same two triggers as they stood before this column, restored on rollback so a downgrade cannot
# leave a clause pointing at a column that has just been dropped.
SHIFT_RESTORED = {
    "core_shift_tenant_insert": (
        "CREATE TRIGGER core_shift_tenant_insert BEFORE INSERT ON core_shift FOR EACH ROW BEGIN "
        "IF (SELECT organization_id FROM core_site WHERE id=NEW.site_id) <> NEW.organization_id "
        "OR (NEW.officer_id IS NOT NULL AND (SELECT organization_id FROM core_person WHERE id=NEW.officer_id) <> NEW.organization_id) "
        "OR (NEW.template_id IS NOT NULL AND (SELECT organization_id FROM core_shifttemplate WHERE id=NEW.template_id) <> NEW.organization_id) "
        "OR (NEW.pay_code_id IS NOT NULL AND (SELECT organization_id FROM core_paycode WHERE id=NEW.pay_code_id) <> NEW.organization_id) "
        "THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='cross-tenant shift reference'; END IF; END"
    ),
    "core_shift_tenant_update": (
        "CREATE TRIGGER core_shift_tenant_update BEFORE UPDATE ON core_shift FOR EACH ROW BEGIN "
        "IF (SELECT organization_id FROM core_site WHERE id=NEW.site_id) <> NEW.organization_id "
        "OR (NEW.officer_id IS NOT NULL AND (SELECT organization_id FROM core_person WHERE id=NEW.officer_id) <> NEW.organization_id) "
        "OR (NEW.template_id IS NOT NULL AND (SELECT organization_id FROM core_shifttemplate WHERE id=NEW.template_id) <> NEW.organization_id) "
        "OR (NEW.pay_code_id IS NOT NULL AND (SELECT organization_id FROM core_paycode WHERE id=NEW.pay_code_id) <> NEW.organization_id) "
        "THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='cross-tenant shift reference'; END IF; END"
    ),
}

# `recorded_by` needs no clause: it is a plain SET_NULL to the user row with no organization to
# disagree with, and every guard in this file is about a reference that could name *another tenant*.
HOLD_OVER_GUARDS = {
    "core_holdover_tenant_insert": (
        "CREATE TRIGGER core_holdover_tenant_insert BEFORE INSERT ON core_holdover FOR EACH ROW BEGIN "
        "IF (SELECT COUNT(*) FROM core_shift s WHERE s.id=NEW.shift_id AND s.organization_id=NEW.organization_id)=0 "
        "OR (NEW.relief_id IS NOT NULL AND (SELECT COUNT(*) FROM core_person p WHERE p.id=NEW.relief_id AND p.organization_id=NEW.organization_id)=0) "
        "THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='cross-tenant hold-over reference'; END IF; END"
    ),
    "core_holdover_tenant_update": (
        "CREATE TRIGGER core_holdover_tenant_update BEFORE UPDATE ON core_holdover FOR EACH ROW BEGIN "
        "IF (SELECT COUNT(*) FROM core_shift s WHERE s.id=NEW.shift_id AND s.organization_id=NEW.organization_id)=0 "
        "OR (NEW.relief_id IS NOT NULL AND (SELECT COUNT(*) FROM core_person p WHERE p.id=NEW.relief_id AND p.organization_id=NEW.organization_id)=0) "
        "THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='cross-tenant hold-over reference'; END IF; END"
    ),
}


def install_tenant_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return
    with schema_editor.connection.cursor() as cursor:
        for name, sql in SHIFT_GUARDS.items():
            cursor.execute(f"DROP TRIGGER IF EXISTS {name}")
            cursor.execute(sql)
        for name, sql in HOLD_OVER_GUARDS.items():
            cursor.execute(f"DROP TRIGGER IF EXISTS {name}")
            cursor.execute(sql)


def remove_tenant_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return
    with schema_editor.connection.cursor() as cursor:
        for name in HOLD_OVER_GUARDS:
            cursor.execute(f"DROP TRIGGER IF EXISTS {name}")
        for name, sql in SHIFT_RESTORED.items():
            cursor.execute(f"DROP TRIGGER IF EXISTS {name}")
            cursor.execute(sql)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_pay_category_history_and_differential'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='relief_for',
            field=models.ForeignKey(blank=True, help_text="Set when this post takes over another officer's tour partway through, or is the second half of it.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relief_halves', to='core.shift'),
        ),
        migrations.CreateModel(
            name='HoldOver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_ends_at', models.DateTimeField(help_text="The post's end as it stood when the tour ran past it. The overrun is measured against this, not against the post's current end, because that is what a dispatcher edits.")),
                ('held_until', models.DateTimeField(blank=True, help_text='When the officer actually came off the post. Blank means they are still on it.', null=True)),
                ('reason', models.CharField(choices=[('relief_no_show', 'Relief did not arrive'), ('relief_late', 'Relief arrived late'), ('unfilled', 'No reliever was ever assigned'), ('incident_open', 'Incident still open at handover'), ('emergency', 'Site emergency or lockdown'), ('other', 'Other (state it)')], max_length=24)),
                ('note', models.TextField(blank=True, help_text="Required for 'Other', and the place for the incident number.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hold_overs', to='core.organization')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hold_overs_recorded', to=settings.AUTH_USER_MODEL)),
                ('relief', models.ForeignKey(blank=True, help_text='Who was supposed to stand the next tour, if anybody was.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relief_failures', to='core.person')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hold_overs', to='core.shift')),
            ],
            options={
                'ordering': ['shift__starts_at', 'created_at'],
            },
        ),
        migrations.RunPython(install_tenant_guards, remove_tenant_guards),
    ]
