# Generated by Django 6.0.8 on 2026-10-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_hold_overs_and_split_tours'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorityscope',
            name='follows_own_branch',
            field=models.BooleanField(default=False, help_text="Scope follows the branch recorded on this person's own file, including after a reassignment."),
        ),
    ]
