# Generated by Django 6.0.8 on 2026-10-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_authority_follows_own_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paycategory',
            name='kind',
            field=models.CharField(choices=[('break', 'Break'), ('holiday', 'Holiday'), ('training', 'Training'), ('travel', 'Travel'), ('double_time', 'Double time'), ('differential', 'Differential'), ('leave', 'Approved leave')], max_length=20),
        ),
    ]
