# Generated by Django 6.0.8 on 2026-10-03 23:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


# A lock segment names a run, and the branch or contract it carves out of it. Left unguarded, a row
# pointing at another company's run would let one firm's payroll approver open or freeze another
# firm's period — the most direct cross-tenant write this product has, since it changes who can edit
# paid time.
#
# Both subject columns are nullable, and every nullable clause is guarded by `IS NOT NULL` before the
# COUNT() test. That is not decoration: `b.id = NULL` matches nothing, so COUNT() is 0, and an
# unguarded clause would refuse every ordinary company-wide segment — the defect migration 0045 had
# to be corrected for, caught only on a real server because sqlite never runs this SQL.
GUARDS = {
    "core_payrolllocksegment_tenant_insert": (
        "CREATE TRIGGER core_payrolllocksegment_tenant_insert BEFORE INSERT ON core_payrolllocksegment FOR EACH ROW BEGIN "
        "IF (SELECT COUNT(*) FROM core_payrollrun r WHERE r.id=NEW.run_id AND r.organization_id=NEW.organization_id)=0 "
        "OR (NEW.branch_id IS NOT NULL AND (SELECT COUNT(*) FROM core_branch b WHERE b.id=NEW.branch_id AND b.organization_id=NEW.organization_id)=0) "
        "OR (NEW.client_id IS NOT NULL AND (SELECT COUNT(*) FROM core_client c WHERE c.id=NEW.client_id AND c.organization_id=NEW.organization_id)=0) "
        "THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='cross-tenant payroll lock segment reference'; END IF; END"
    ),
    "core_payrolllocksegment_tenant_update": (
        "CREATE TRIGGER core_payrolllocksegment_tenant_update BEFORE UPDATE ON core_payrolllocksegment FOR EACH ROW BEGIN "
        "IF (SELECT COUNT(*) FROM core_payrollrun r WHERE r.id=NEW.run_id AND r.organization_id=NEW.organization_id)=0 "
        "OR (NEW.branch_id IS NOT NULL AND (SELECT COUNT(*) FROM core_branch b WHERE b.id=NEW.branch_id AND b.organization_id=NEW.organization_id)=0) "
        "OR (NEW.client_id IS NOT NULL AND (SELECT COUNT(*) FROM core_client c WHERE c.id=NEW.client_id AND c.organization_id=NEW.organization_id)=0) "
        "THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='cross-tenant payroll lock segment reference'; END IF; END"
    ),
}


def install_tenant_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return
    with schema_editor.connection.cursor() as cursor:
        for name, sql in GUARDS.items():
            cursor.execute(f"DROP TRIGGER IF EXISTS {name}")
            cursor.execute(sql)


def remove_tenant_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return
    with schema_editor.connection.cursor() as cursor:
        for name in GUARDS:
            cursor.execute(f"DROP TRIGGER IF EXISTS {name}")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_leave_pay_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollLockSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('open', 'Open for correction')], default='locked', max_length=10)),
                ('reason', models.CharField(help_text='Why this slice differs from the run. Read months later by somebody who was not in the room.', max_length=255)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_lock_segments', to='core.branch')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payroll_lock_segments', to='core.client')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_lock_decisions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_lock_segments', to='core.organization')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lock_segments', to='core.payrollrun')),
            ],
            options={
                'ordering': ['run__period_start', 'branch__name', 'client__name'],
                'constraints': [models.UniqueConstraint(fields=('run', 'branch'), name='one_lock_segment_per_run_branch'), models.UniqueConstraint(fields=('run', 'client'), name='one_lock_segment_per_run_client')],
            },
        ),
        migrations.RunPython(install_tenant_guards, remove_tenant_guards),
    ]
