# Generated by Django 6.0.8 on 2026-10-04 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_payroll_lock_segments'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='approved_role_domains',
            field=models.JSONField(blank=True, default=list, help_text="Email domains allowed to hold a role other than Officer, e.g. ['guardco.com']. Empty allows any identity; Officers may always link a personal address."),
        ),
    ]
