# Generated by Django 6.0.8 on 2026-10-04 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_approved_role_domains'),
    ]

    operations = [
        migrations.AddField(
            model_name='persondocument',
            name='verified_type',
            field=models.CharField(blank=True, default='', help_text="MIME proved from the file's own bytes at upload. Blank means never verified.", max_length=100),
        ),
    ]
