# Generated by Django 6.0.8 on 2026-10-04 01:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


# A station belongs to one company and stands at one of that company's posts. The site reference is the
# only place a kiosk row can be made to lie about geography, and a station planted at another firm's
# post would put this firm's officers' time on that property — so the guard is on the pair, as it is on
# every other tenant-owned row here.
#
# `site_id` is nullable and the clause is preceded by `IS NOT NULL`. Without it, `s.id = NULL` matches
# nothing, COUNT(*) is 0, and every station without a post of its own is refused at creation — the
# defect migrations 0045 and 0048 both had to be corrected for, invisible on sqlite because it never
# runs this SQL.
GUARDS = {
    "core_clockkiosk_tenant_insert": (
        "CREATE TRIGGER core_clockkiosk_tenant_insert BEFORE INSERT ON core_clockkiosk FOR EACH ROW BEGIN "
        "IF (NEW.site_id IS NOT NULL AND (SELECT COUNT(*) FROM core_site s WHERE s.id=NEW.site_id AND s.organization_id=NEW.organization_id)=0) "
        "THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='cross-tenant clock kiosk reference'; END IF; END"
    ),
    "core_clockkiosk_tenant_update": (
        "CREATE TRIGGER core_clockkiosk_tenant_update BEFORE UPDATE ON core_clockkiosk FOR EACH ROW BEGIN "
        "IF (NEW.site_id IS NOT NULL AND (SELECT COUNT(*) FROM core_site s WHERE s.id=NEW.site_id AND s.organization_id=NEW.organization_id)=0) "
        "THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='cross-tenant clock kiosk reference'; END IF; END"
    ),
}


def install_tenant_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return
    with schema_editor.connection.cursor() as cursor:
        for name, sql in GUARDS.items():
            cursor.execute(f"DROP TRIGGER IF EXISTS {name}")
            cursor.execute(sql)


def remove_tenant_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return
    with schema_editor.connection.cursor() as cursor:
        for name in GUARDS:
            cursor.execute(f"DROP TRIGGER IF EXISTS {name}")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_document_verified_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClockKiosk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='person',
            name='clock_pin',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='person',
            name='clock_pin_index',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='person',
            name='pin_failed_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='pin_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='pin_set_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timepolicy',
            name='allow_kiosk',
            field=models.BooleanField(default=True, help_text='Allow a shared clock station at this company. Turn off to require each officer to clock from their own device.'),
        ),
        migrations.AddField(
            model_name='timepolicyoverride',
            name='allow_kiosk',
            field=models.BooleanField(blank=True, help_text='Leave unset to inherit the company rule.', null=True),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(condition=models.Q(('clock_pin_index', ''), _negated=True), fields=('organization', 'clock_pin_index'), name='unique_clock_pin_in_org'),
        ),
        migrations.AddField(
            model_name='clockkiosk',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clock_kiosks_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clockkiosk',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clock_kiosks', to='core.organization'),
        ),
        migrations.AddField(
            model_name='clockkiosk',
            name='site',
            field=models.ForeignKey(blank=True, help_text='Where the station physically stands. A punch taken here is placed at this post.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clock_kiosks', to='core.site'),
        ),
        migrations.AddConstraint(
            model_name='clockkiosk',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_kiosk_name_in_org'),
        ),
        migrations.RunPython(install_tenant_guards, remove_tenant_guards),
    ]
