# Generated by Django 6.0.8 on 2026-10-04 02:11

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


# REC-4. The delete guard from 0018 said "never", and it was right until retention had to be enforced.
# This version keeps the refusal for every session that has not named a seal, and admits one sanctioned
# path: the session variable must hold the id of an AuditSeal row whose own period covers the row being
# removed, in the same organization. Three consequences worth stating, because they are the point:
#
#   * a query console cannot delete a single inconvenient event — the whole period has to have been
#     sealed first, and the seal is append-only evidence that it was;
#   * a seal does not unlock an arbitrary range: rows outside its period are still immutable;
#   * the guard is a trigger, so it holds against raw SQL that never passes through Django. There is no
#     equivalent on sqlite, which is why services.purge_sealed_audit re-checks every precondition in
#     Python too and why this was probed against a real MySQL 8.4 rather than assumed.
#
# The variable is compared with REPLACE(...,'-','') so either UUID spelling names a seal; the columns are
# char(32) and a dashed value does not fit one.
IMMUTABLE = ("CREATE TRIGGER core_audit_no_delete BEFORE DELETE ON core_auditevent FOR EACH ROW "
             "SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='audit events are immutable'")
SEALED_DELETE = (
    "CREATE TRIGGER core_audit_no_delete BEFORE DELETE ON core_auditevent FOR EACH ROW BEGIN "
    "IF @audit_purge_seal IS NULL OR NOT EXISTS ("
    "SELECT 1 FROM core_auditseal s WHERE s.id=REPLACE(@audit_purge_seal,'-','') "
    "AND s.organization_id=OLD.organization_id "
    "AND OLD.occurred_at >= s.period_start AND OLD.occurred_at <= s.period_end"
    ") THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='audit events are immutable'; "
    "END IF; END"
)


def install_seal_aware_guard(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DROP TRIGGER IF EXISTS core_audit_no_delete")
        cursor.execute(SEALED_DELETE)


def restore_absolute_guard(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DROP TRIGGER IF EXISTS core_audit_no_delete")
        cursor.execute(IMMUTABLE)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_kiosk_pin_and_station'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditSeal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('first_previous', models.CharField(blank=True, max_length=64)),
                ('first_hash', models.CharField(max_length=64)),
                ('last_hash', models.CharField(max_length=64)),
                ('event_count', models.PositiveIntegerField()),
                ('redaction_count', models.PositiveIntegerField(default=0)),
                ('manifest', models.JSONField(default=list, help_text='Per-action counts for the period, so a seal reads as something without opening the archive.')),
                ('archive', models.FileField(blank=True, upload_to=core.models.audit_seal_path)),
                ('archive_sha256', models.CharField(max_length=64)),
                ('archive_bytes', models.BigIntegerField(default=0)),
                ('retention_days', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('sealed', 'Archived; rows still live'), ('purged', 'Archived; rows removed from the live table')], default='sealed', max_length=10)),
                ('sealed_at', models.DateTimeField(auto_now_add=True)),
                ('purged_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_seals', to='core.organization')),
                ('purged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_seals_purged', to=settings.AUTH_USER_MODEL)),
                ('sealed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_seals_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['period_start'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'period_end'), name='one_seal_per_period')],
            },
        ),
        migrations.RunPython(install_seal_aware_guard, restore_absolute_guard),
    ]
