# Generated by Django 6.0.8 on 2026-10-04 03:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


# NTF-4's two tenant-linked tables, guarded like every other table that names a row of another kind.
#
# A consent ledger pointing at another company's officer would let one firm's opt-in decide whether
# another firm may text somebody — the worst available use of a cross-tenant write, because the harm is
# regulatory and lands on the company that did not do it. A delivery event pointing at another
# company's notice would mark their message bounced on our say-so.
#
# ``person_id`` and ``notification_id`` are both nullable, and every nullable clause is preceded by
# ``IS NOT NULL`` before the COUNT() test. Without it, `p.id = NULL` matches nothing, COUNT() is 0, and
# a consent recorded against a person who has since been deleted from the roster — which the ledger
# deliberately keeps, because the proof outlives the account — would be refused. That is the 0045
# defect again, and sqlite cannot see it because it never runs this SQL.
GUARDS = {
    "core_messageconsent_tenant_insert": (
        "CREATE TRIGGER core_messageconsent_tenant_insert BEFORE INSERT ON core_messageconsent FOR EACH ROW BEGIN "
        "IF (NEW.person_id IS NOT NULL AND (SELECT COUNT(*) FROM core_person p WHERE p.id=NEW.person_id AND p.organization_id=NEW.organization_id)=0) "
        "THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='cross-tenant message consent reference'; END IF; END"
    ),
    "core_messageconsent_tenant_update": (
        "CREATE TRIGGER core_messageconsent_tenant_update BEFORE UPDATE ON core_messageconsent FOR EACH ROW BEGIN "
        "IF (NEW.person_id IS NOT NULL AND (SELECT COUNT(*) FROM core_person p WHERE p.id=NEW.person_id AND p.organization_id=NEW.organization_id)=0) "
        "THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='cross-tenant message consent reference'; END IF; END"
    ),
    "core_deliveryevent_tenant_insert": (
        "CREATE TRIGGER core_deliveryevent_tenant_insert BEFORE INSERT ON core_deliveryevent FOR EACH ROW BEGIN "
        "IF (NEW.notification_id IS NOT NULL AND (SELECT COUNT(*) FROM core_notification n WHERE n.id=NEW.notification_id AND n.organization_id=NEW.organization_id)=0) "
        "THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='cross-tenant delivery event reference'; END IF; END"
    ),
    "core_deliveryevent_tenant_update": (
        "CREATE TRIGGER core_deliveryevent_tenant_update BEFORE UPDATE ON core_deliveryevent FOR EACH ROW BEGIN "
        "IF (NEW.notification_id IS NOT NULL AND (SELECT COUNT(*) FROM core_notification n WHERE n.id=NEW.notification_id AND n.organization_id=NEW.organization_id)=0) "
        "THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='cross-tenant delivery event reference'; END IF; END"
    ),
}


def install_tenant_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return
    with schema_editor.connection.cursor() as cursor:
        for name, sql in GUARDS.items():
            cursor.execute(f"DROP TRIGGER IF EXISTS {name}")
            cursor.execute(sql)


def remove_tenant_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return
    with schema_editor.connection.cursor() as cursor:
        for name in GUARDS:
            cursor.execute(f"DROP TRIGGER IF EXISTS {name}")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_audit_seal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    operations = [
        migrations.AddField(
            model_name='notification',
            name='mandatory',
            field=models.BooleanField(default=False, help_text='Required operational or security notice. Optional notices obey unsubscribes and bounces; this one still goes by email, but never by text to an opted-out number.'),
        ),
        migrations.AddField(
            model_name='organization',
            name='webhook_token',
            field=models.CharField(blank=True, help_text="Address half of this company's provider callbacks. Rotate it if it appears in a log.", max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('read', 'Read'), ('blocked', 'Not sent — consent or suppression')], default='queued', max_length=20),
        ),
        migrations.CreateModel(
            name='DeliveryEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=30)),
                ('channel', models.CharField(choices=[('sms', 'Text message'), ('email', 'Email')], default='sms', max_length=20)),
                ('destination', models.CharField(max_length=320)),
                ('kind', models.CharField(choices=[('accepted', 'Accepted by the provider'), ('delivered', 'Delivered'), ('bounce', 'Bounced'), ('complaint', 'Complaint or spam report'), ('unsubscribe', 'Unsubscribe request'), ('inbound', 'A message sent to us'), ('failed', 'Could not be delivered'), ('status', 'Some other status change')], max_length=20)),
                ('message_reference', models.CharField(blank=True, help_text="The provider's own id for the message, so a support ticket can find it.", max_length=160)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('applied', models.BooleanField(default=False, help_text='Whether this callback changed a send or a consent.')),
                ('verified', models.BooleanField(default=False, help_text='Signed by the provider, as opposed to delivered to the right token.')),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_events', to='core.notification')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_events', to='core.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'channel', 'destination'], name='core_delive_organiz_4cda52_idx')],
            },
        ),
        migrations.CreateModel(
            name='MessageConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('sms', 'Text message'), ('email', 'Email')], default='sms', max_length=20)),
                ('destination', models.CharField(help_text='The number or address this decision is about. Consent travels with it, not with the person.', max_length=320)),
                ('state', models.CharField(choices=[('granted', 'Opted in'), ('revoked', 'Opted out')], max_length=10)),
                ('source', models.CharField(choices=[('signup', 'Accepted with the account'), ('profile', "The officer's own settings"), ('first_login', 'Answered on first sign-in'), ('provider_keyword', 'A reply to the number itself'), ('import', 'A roster import column'), ('admin', "A manager, on the officer's behalf"), ('officer_record', 'Stated on the paper application')], default='profile', max_length=24)),
                ('wording', models.TextField(blank=True, help_text='The disclosure shown when the answer was given, recorded as shown.')),
                ('evidence', models.JSONField(blank=True, default=dict, help_text='How the answer arrived: surface, acting user, provider message id, source IP.')),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_consents', to='core.organization')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_consents', to='core.person')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_consents_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-decided_at', '-created_at'],
                'indexes': [models.Index(fields=['organization', 'channel', 'destination'], name='core_messag_organiz_e694b9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Suppression',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('sms', 'Text message'), ('email', 'Email')], default='sms', max_length=20)),
                ('destination', models.CharField(max_length=320)),
                ('kind', models.CharField(choices=[('hard_bounce', 'Mailbox rejected the message'), ('unknown_number', 'Number is not in service'), ('unsubscribe', 'Asked not to receive these'), ('complaint', 'Marked as spam'), ('manual', 'Blocked by an administrator')], max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('provider', models.CharField(blank=True, max_length=30)),
                ('source_reference', models.CharField(blank=True, help_text='The provider id or message that produced this block.', max_length=120)),
                ('since', models.DateTimeField(auto_now_add=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('cleared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppressions_cleared', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppressions', to='core.organization')),
            ],
            options={
                'ordering': ['-since'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'channel', 'destination'), name='one_suppression_per_destination')],
            },
        ),
        migrations.RunPython(install_tenant_guards, remove_tenant_guards),
    ]
