# Generated by Django 6.0.8 on 2026-10-04 13:52
#
# NTF-1, NTF-2 and CLK-4 together, and deliberately no `RunPython` guard block. Every tenant guard in
# this project protects a *nullable* foreign key that can be pointed at another company's row
# (`MessageConsent.person`, `DeliveryEvent.notification`, `HoldOver.relief`). Nothing here adds one:
# `ChannelRule.organization` is non-null and CASCADE, its `created_by` is an account rather than a
# tenant-owned record, and the five added columns carry no references at all. A guard invented to
# match the neighbours would be dead SQL that still has to be tested.
#
# `ChannelRule`'s unique constraint is unconditional (organization, audience, family, event_type) with
# `event_type` defaulting to the empty string rather than NULL, precisely so MySQL *can* enforce it —
# the conditional uniques elsewhere in this schema are silently skipped (models.W036), which is why
# `set_clock_pin` has to check its own collision in Python. Here the database does it, and
# `ChannelRuleForm.clean` still checks first so an operator gets a message instead of an IntegrityError.

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_messaging_consent_lifecycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialtype',
            name='escalate_after_days',
            field=models.PositiveIntegerField(blank=True, help_text='Once the countdown reaches this many days before expiry, the notice goes to the escalation roles as well. Set it to one of the lead times above, or nothing changes is missed.', null=True),
        ),
        migrations.AddField(
            model_name='credentialtype',
            name='escalate_to',
            field=models.JSONField(blank=True, default=list, help_text='Roles to pull in when a lower rung went unanswered. Empty means no escalation.'),
        ),
        migrations.AddField(
            model_name='punch',
            name='risk_flags',
            field=models.JSONField(blank=True, default=list, help_text='Location-plausibility signals this punch tripped. Empty means none, not unchecked.'),
        ),
        migrations.AddField(
            model_name='timepolicy',
            name='flag_spoof_risk',
            field=models.BooleanField(default=True, help_text='Send punches with an implausible location reading to time review. Never blocks the clock.'),
        ),
        migrations.AddField(
            model_name='timepolicyoverride',
            name='flag_spoof_risk',
            field=models.BooleanField(blank=True, help_text='Leave unset to inherit the company rule.', null=True),
        ),
        migrations.CreateModel(
            name='ChannelRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audience', models.CharField(choices=[('subject', 'The person the notice is about'), ('compliance', 'Owner, administrator, HR / compliance'), ('dispatch', 'Scheduler, dispatcher, site supervisor'), ('payroll', 'Payroll approver'), ('audit', 'Read-only auditor'), ('worker', 'Any other recipient')], max_length=20)),
                ('family', models.CharField(choices=[('credential', 'Credentials and compliance'), ('training', 'Training'), ('punch', 'Clock punches and exceptions'), ('shift', 'Posts, swaps and trades'), ('timeoff', 'Time off'), ('payroll', 'Payroll periods'), ('document', 'Documents and acknowledgments'), ('retention', 'Retention, holds and disposal'), ('membership', 'Accounts and invitations'), ('onboarding', 'Onboarding tasks'), ('import', 'Data imports'), ('audit', 'Audit history and sealing'), ('message', 'Text-message consent'), ('organization', 'Company settings')], max_length=20)),
                ('event_type', models.CharField(blank=True, help_text='Leave empty to cover the whole family.', max_length=100)),
                ('channels', models.JSONField(blank=True, default=list, help_text='Email, SMS, or neither (in-app only). In-app always arrives and cannot be switched off.')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_rules', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_rules', to='core.organization')),
            ],
            options={
                'ordering': ['audience', 'family', 'event_type'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'audience', 'family', 'event_type'), name='one_channel_rule_per_audience_and_event')],
            },
        ),
    ]
