# Generated by Django 6.0.8 on 2026-10-04 17:44
#
# CLK-1. Two new policy booleans, one new *nullable foreign key* on the punch, and a fourth value on
# the record-sensitivity ladder. The nullable FK is the only one of those that a trigger has to police,
# and the reason it is not optional is specific to this column: `punch.selfie` points at a
# `PersonDocument`, which is itself tenant-owned, so an unguarded write could hang one company's clock
# evidence off another company's personnel record — and the harm is not a stray row but a face photo
# disclosed across a tenant line, the exact thing the `biometric` rung below exists to prevent.
#
# The `NEW.selfie_id IS NOT NULL AND …` prefix is load-bearing, not decoration. On a nullable FK,
# `p.id = NULL` matches nothing, so the bare `COUNT(*) = 0` test would be true for every punch with no
# photo, and the trigger would refuse the ordinary case — which is the 0045 defect, and invisible on
# sqlite because sqlite never runs this SQL.
#
# The biometric rung itself needs no migration-side work: `sensitivity` is a varchar choice, so the
# AlterField below is metadata and no existing row changes meaning — no record was previously
# `biometric`, so nothing is re-classified by this landing.

import django.db.models.deletion
from django.db import migrations, models

GUARDS = {
    "core_punch_selfie_tenant_insert": (
        "CREATE TRIGGER core_punch_selfie_tenant_insert BEFORE INSERT ON core_punch FOR EACH ROW BEGIN "
        "IF (NEW.selfie_id IS NOT NULL AND (SELECT COUNT(*) FROM core_persondocument d WHERE d.id=NEW.selfie_id AND d.organization_id=NEW.organization_id)=0) "
        "THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='cross-tenant punch selfie reference'; END IF; END"
    ),
    "core_punch_selfie_tenant_update": (
        "CREATE TRIGGER core_punch_selfie_tenant_update BEFORE UPDATE ON core_punch FOR EACH ROW BEGIN "
        "IF (NEW.selfie_id IS NOT NULL AND (SELECT COUNT(*) FROM core_persondocument d WHERE d.id=NEW.selfie_id AND d.organization_id=NEW.organization_id)=0) "
        "THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='cross-tenant punch selfie reference'; END IF; END"
    ),
}


def install_selfie_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return
    with schema_editor.connection.cursor() as cursor:
        for name, sql in GUARDS.items():
            cursor.execute(f"DROP TRIGGER IF EXISTS {name}")
            cursor.execute(sql)


def remove_selfie_guards(apps, schema_editor):
    if schema_editor.connection.vendor != "mysql":
        return
    with schema_editor.connection.cursor() as cursor:
        for name in GUARDS:
            cursor.execute(f"DROP TRIGGER IF EXISTS {name}")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_channel_rules_and_spoof_risk'),
    ]

    operations = [
        migrations.AddField(
            model_name='punch',
            name='selfie',
            field=models.ForeignKey(blank=True, help_text='The clock photo captured for this punch. Blank means none was attached.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selfie_punches', to='core.persondocument'),
        ),
        migrations.AddField(
            model_name='timepolicy',
            name='require_selfie',
            field=models.BooleanField(default=False, help_text='Ask for a photo at clock-in and clock-out when no station PIN or checkpoint scan covers the punch. A punch without one is still recorded; it goes to time review.'),
        ),
        migrations.AddField(
            model_name='timepolicyoverride',
            name='require_selfie',
            field=models.BooleanField(blank=True, help_text='Leave unset to inherit the company rule.', null=True),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='sensitivity',
            field=models.CharField(choices=[('standard', 'Personnel file'), ('restricted', 'Restricted'), ('sealed', 'Sealed'), ('biometric', 'Biometric')], default='standard', help_text='Who may open a record of this type, in addition to its audience.', max_length=20),
        ),
        migrations.RunPython(install_selfie_guards, remove_selfie_guards),
    ]
