# Generated by Django 6.0.8 on 2026-10-05 16:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_approval_gates_enforcement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingitem',
            name='signing_template_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onboardingitem',
            name='signing_template_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='onboardingitem',
            name='kind',
            field=models.CharField(choices=[('task', 'A step someone marks done'), ('document', 'A record filed in the personnel file'), ('signature', 'A document signed in DocuSeal'), ('credential', 'A numbered registration or commission on file')], default='task', max_length=20),
        ),
        migrations.CreateModel(
            name='SigningRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt', models.PositiveIntegerField()),
                ('template_id', models.PositiveBigIntegerField()),
                ('template_snapshot', models.JSONField(default=dict)),
                ('signer_email', models.EmailField(max_length=254)),
                ('signer_name', models.CharField(max_length=255)),
                ('base_url', models.URLField(max_length=255)),
                ('submission_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('submitter_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('signing_slug', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('preparing', 'Checking submission creation'), ('sent', 'Awaiting signature'), ('completed', 'Signed and filed'), ('declined', 'Declined or expired'), ('rejected', 'Not created; correct settings and resend')], default='preparing', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('next_check_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('failures', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.documenttype')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signing_requests', to='core.organization')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signing_requests', to='core.onboardingtask')),
            ],
            options={
                'ordering': ['-created_at', '-attempt'],
            },
        ),
        migrations.CreateModel(
            name='SignedArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=255)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='signed_artifact', to='core.persondocument')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artifacts', to='core.signingrequest')),
            ],
        ),
        migrations.CreateModel(
            name='SigningSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField(max_length=255)),
                ('encrypted_api_key', models.TextField()),
                ('enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signing_settings', to='core.organization')),
            ],
        ),
        migrations.AddIndex(
            model_name='signingrequest',
            index=models.Index(fields=['status', 'next_check_at'], name='core_signing_due'),
        ),
        migrations.AddConstraint(
            model_name='signingrequest',
            constraint=models.UniqueConstraint(fields=('task', 'attempt'), name='one_signing_attempt_per_task'),
        ),
        migrations.AddConstraint(
            model_name='signingrequest',
            constraint=models.UniqueConstraint(fields=('organization', 'submission_id'), name='one_signing_submission_per_org'),
        ),
        migrations.AddConstraint(
            model_name='signedartifact',
            constraint=models.UniqueConstraint(fields=('request', 'key'), name='one_artifact_per_signing_request'),
        ),
    ]
