# Generated by Django 6.0.8 on 2026-10-05 23:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_signing_tenant_guards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='occurred_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
    ]
