# Generated by Django 6.0.8 on 2026-10-06 18:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_audit_event_monotonic_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notice_key', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_templates', to='core.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['notice_key'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'notice_key'), name='one_sms_template_per_notice')],
            },
        ),
    ]
