# Generated by Django 6.0.8 on 2026-10-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_sms_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='default_post_orders',
            field=models.TextField(blank=True, help_text='Leave unchanged or empty to use company orders. Edited text overrides them for this client.'),
        ),
        migrations.AddField(
            model_name='organization',
            name='default_post_orders',
            field=models.TextField(blank=True, help_text='Company-wide orders used when the client, site and post have no override.'),
        ),
        migrations.AddField(
            model_name='site',
            name='default_post_orders',
            field=models.TextField(blank=True, help_text='Leave unchanged or empty to inherit client or company orders. Edited text overrides them for this site.'),
        ),
    ]
