# Generated by Django 6.0.8 on 2026-10-07 19:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_email_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='holdover',
            name='expected_release_at',
            field=models.DateTimeField(blank=True, help_text='Authorized expected departure, not an actual clock-out. Live departure alerts use this deadline; an open hold-over without one remains explicitly awaiting relief.', null=True),
        ),
        migrations.AddField(
            model_name='holdover',
            name='officer',
            field=models.ForeignKey(blank=True, help_text='Officer authorized to remain, captured when recording the hold-over. Legacy rows without a snapshot apply to the post.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hold_overs_worked', to='core.person'),
        ),
        migrations.AddField(
            model_name='timepolicy',
            name='arrival_alert_enabled',
            field=models.BooleanField(default=False, help_text='Raise a live case when an assigned officer has no clock-in after the arrival grace period. Does not change pay.'),
        ),
        migrations.AddField(
            model_name='timepolicy',
            name='arrival_grace_minutes',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(240)]),
        ),
        migrations.AddField(
            model_name='timepolicy',
            name='departure_alert_enabled',
            field=models.BooleanField(default=False, help_text='Raise a live case when a clocked-in officer has no clock-out after the departure grace period. Approved hold-overs move the deadline.'),
        ),
        migrations.AddField(
            model_name='timepolicy',
            name='departure_grace_minutes',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(240)]),
        ),
        migrations.AddField(
            model_name='timepolicyoverride',
            name='arrival_alert_enabled',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timepolicyoverride',
            name='arrival_grace_minutes',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Blank inherits; zero alerts immediately after the scheduled start. Maximum 240 minutes.', null=True, validators=[django.core.validators.MaxValueValidator(240)]),
        ),
        migrations.AddField(
            model_name='timepolicyoverride',
            name='departure_alert_enabled',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timepolicyoverride',
            name='departure_grace_minutes',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Blank inherits; zero alerts immediately after the expected departure. Maximum 240 minutes.', null=True, validators=[django.core.validators.MaxValueValidator(240)]),
        ),
        migrations.CreateModel(
            name='AttendanceCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('arrival', 'Late arrival'), ('departure', 'Overdue departure')], max_length=12)),
                ('status', models.CharField(choices=[('open', 'Needs follow-up'), ('resolved', 'Resolved')], default='open', max_length=12)),
                ('deadline_at', models.DateTimeField()),
                ('policy_snapshot', models.JSONField(default=dict)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.CharField(blank=True, max_length=200)),
                ('manager_closed', models.BooleanField(default=False)),
                ('cycle', models.PositiveIntegerField(default=1)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_cases', to='core.organization')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_cases', to='core.person')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_cases', to='core.shift')),
            ],
            options={
                'ordering': ['opened_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceCaseAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('opened', 'Alert raised'), ('contact', 'Contact recorded'), ('relief', 'Relief coordination recorded'), ('hold_over', 'Hold-over approved'), ('resolved', 'Automatically resolved'), ('closed', 'Closed after manager review')], max_length=16)),
                ('note', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.attendancecase')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='attendancecase',
            constraint=models.UniqueConstraint(fields=('shift', 'person', 'kind'), name='one_attendance_case_per_assignment'),
        ),
    ]
