# Generated by Django 6.0.8 on 2026-10-07 19:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_live_attendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='holdover',
            name='sequence',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='holdover',
            constraint=models.UniqueConstraint(fields=('shift', 'sequence'), name='holdover_shift_sequence'),
        ),
    ]
