# Generated by Django 6.0.8 on 2026-10-07 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_hold_over_sequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='handgun_qualification',
            field=models.CharField(blank=True, choices=[('semi_auto', 'Semi-automatic pistol'), ('revolver', 'Revolver only'), ('none', 'Not qualified')], help_text='Recorded range qualification for this credential. Blank means not recorded; revolver-only is not semi-automatic qualification.', max_length=16),
        ),
        migrations.AddField(
            model_name='credential',
            name='license_level',
            field=models.CharField(blank=True, help_text='License / registration level, if not already identified by the credential type (for example Level III).', max_length=60),
        ),
        migrations.AddField(
            model_name='credential',
            name='shotgun_qualification',
            field=models.CharField(blank=True, choices=[('qualified', 'Qualified / patterned'), ('not_qualified', 'Not qualified / not patterned')], help_text='Recorded shotgun patterning / qualification. Blank means not recorded, not permission to carry.', max_length=16),
        ),
        migrations.AddField(
            model_name='person',
            name='birth_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='birth_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='county',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='mailing_address_line1',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='person',
            name='mailing_address_line2',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='person',
            name='mailing_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='mailing_postal_code',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='person',
            name='mailing_state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='person',
            name='middle_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='person',
            name='name_suffix',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='person',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.CreateModel(
            name='PrivatePersonnelDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_payload', models.TextField(blank=True)),
                ('ssn_last_four', models.CharField(blank=True, editable=False, max_length=4)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_personnel_details', to='core.organization')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='private_details', to='core.person')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
