# Generated by Django 6.0.8 on 2026-10-07 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_personnel_identity_and_private_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='license_level',
        ),
    ]
