# Generated by Django 6.0.8 on 2026-10-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_remove_redundant_license_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='eligible_for_rehire',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('onboarding', 'Onboarding'), ('inactive', 'Inactive'), ('terminated', 'Terminated')], default='onboarding', max_length=20),
        ),
    ]
