# Generated by Django 6.0.8 on 2026-10-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_personnel_termination_and_rehire'),
    ]

    operations = [
        migrations.AddField(
            model_name='punch',
            name='break_paid',
            field=models.BooleanField(default=True, help_text='Breaks are paid unless explicitly classified as unpaid by an authorized reviewer.'),
        ),
        migrations.AddField(
            model_name='punch',
            name='break_pay_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='punch',
            name='kind',
            field=models.CharField(choices=[('in', 'Clock in'), ('out', 'Clock out'), ('checkpoint', 'Checkpoint'), ('break_start', 'Start break'), ('break_end', 'End break')], max_length=20),
        ),
    ]
