# Generated by Django 6.0.8 on 2026-10-07 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_explicit_break_punches'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='sms_privacy_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name='organization',
            name='sms_terms_url',
            field=models.URLField(blank=True, max_length=2048),
        ),
    ]
