# Generated by Django 6.0.8 on 2026-10-08 15:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_sms_program_disclosures'),
    ]

    operations = [
        migrations.AddField(
            model_name='timepolicy',
            name='pay_period_anchor',
            field=models.DateField(blank=True, help_text='An actual pay-period start date on the workweek starting weekday. Required for multi-week periods.', null=True),
        ),
        migrations.AddField(
            model_name='timepolicy',
            name='pay_period_weeks',
            field=models.PositiveSmallIntegerField(default=1, help_text='Length of a calculated pay period in whole weeks. Does not change weekly overtime.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)]),
        ),
        migrations.CreateModel(
            name='PersonnelAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('last_shift_end', models.DateTimeField(blank=True, null=True)),
                ('roster_access_until', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roster_assignments', to='core.client')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel_assignments', to='core.organization')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_assignments', to='core.person')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roster_assignments', to='core.site')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('client__isnull', False), ('site__isnull', True)), models.Q(('client__isnull', True), ('site__isnull', False)), _connector='OR'), name='personnel_assignment_one_target'), models.UniqueConstraint(fields=('person', 'client'), name='unique_personnel_client_assignment'), models.UniqueConstraint(fields=('person', 'site'), name='unique_personnel_site_assignment')],
            },
        ),
    ]
