# Generated by Django 6.0.8 on 2026-10-08 20:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_personnel_rosters_and_pay_periods'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='timeoffrequest',
            name='confirmed_leave_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='timeoffrequest',
            name='use_leave_bank',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='LeaveAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eligible_from', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrolled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_accounts', to='core.organization')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leave_account', to='core.person')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('pay_rate', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(0)])),
                ('multiplier', models.DecimalField(decimal_places=2, max_digits=5)),
                ('policy_revision', models.PositiveIntegerField()),
                ('consumed', models.BooleanField(default=False)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_days', to='core.timeoffrequest')),
            ],
            options={
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='LeaveEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('grant', 'Annual grant'), ('accrual', 'Earned accrual'), ('adjustment', 'HR adjustment'), ('expiry', 'Year-end expiry'), ('reserve', 'Approved reservation'), ('release', 'Release / refund')], max_length=16)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=9)),
                ('effective_on', models.DateField()),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.leaveaccount')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_entries', to='core.timeoffrequest')),
            ],
            options={
                'ordering': ['-effective_on', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('annual_hours', models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(0)])),
                ('grant_method', models.CharField(choices=[('annual', 'Annual upfront grant (prorated at enrollment)'), ('accrual', 'Accrue after each completed pay period'), ('manual', 'Manual HR grants')], default='manual', max_length=12)),
                ('daily_hours', models.DecimalField(decimal_places=2, default=8, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)])),
                ('carryover_cap', models.DecimalField(decimal_places=2, default=0, help_text='Zero expires unused available hours; otherwise carry over up to this cap.', max_digits=9, validators=[django.core.validators.MinValueValidator(0)])),
                ('fallback_pay_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leave_policy', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_hours', models.DecimalField(decimal_places=2, max_digits=7)),
                ('paid_hours', models.DecimalField(decimal_places=2, max_digits=7)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='core.leaveday')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_usages', to='core.payrollrun')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('annual_hours', models.DecimalField(decimal_places=2, max_digits=9)),
                ('grant_method', models.CharField(choices=[('annual', 'Annual upfront grant (prorated at enrollment)'), ('accrual', 'Accrue after each completed pay period'), ('manual', 'Manual HR grants')], max_length=12)),
                ('carryover_cap', models.DecimalField(decimal_places=2, max_digits=9)),
                ('pay_period_weeks', models.PositiveSmallIntegerField()),
                ('pay_period_anchor', models.DateField()),
                ('timezone', models.CharField(max_length=64)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='years', to='core.leaveaccount')),
            ],
        ),
        migrations.AddConstraint(
            model_name='leaveday',
            constraint=models.UniqueConstraint(fields=('request', 'day'), name='unique_leave_request_day'),
        ),
        migrations.AddConstraint(
            model_name='leaveentry',
            constraint=models.UniqueConstraint(fields=('account', 'key'), name='unique_leave_entry_key'),
        ),
        migrations.AddConstraint(
            model_name='leaveusage',
            constraint=models.UniqueConstraint(fields=('day', 'run'), name='unique_leave_usage_run_day'),
        ),
        migrations.AddConstraint(
            model_name='leaveyear',
            constraint=models.UniqueConstraint(fields=('account', 'year'), name='unique_leave_account_year'),
        ),
    ]
