from django.urls import path
from . import views
from . import signing_views
from . import workspace_views

urlpatterns = [
    # Workspace navigation: role-based landing pages
    path("workspace/today/", workspace_views.workspace_today, name="workspace_today"),
    path("workspace/people/", workspace_views.workspace_people, name="workspace_people"),
    path("workspace/schedule/", workspace_views.workspace_schedule, name="workspace_schedule"),
    path("workspace/payroll/", workspace_views.workspace_payroll, name="workspace_payroll"),
    path("workspace/compliance/", workspace_views.workspace_compliance, name="workspace_compliance"),
    path("workspace/reports/", workspace_views.workspace_reports, name="workspace_reports"),
    
    # Signing
    path("onboarding/signing/", signing_views.signing_queue, name="signing_queue"),
    path("settings/signing/", signing_views.signing_settings, name="signing_settings"),
    path("onboarding/tasks/<uuid:task_id>/signing/send/", signing_views.signing_send, name="signing_send"),
    path("onboarding/tasks/<uuid:task_id>/signing/refresh/", signing_views.signing_refresh, name="signing_refresh"),
    path("onboarding/tasks/<uuid:task_id>/signing/open/", signing_views.signing_open, name="signing_open"),
    path("onboarding/tasks/<uuid:task_id>/signing/return/", signing_views.signing_return, name="signing_return"),
    
    # Health and utilities
    path("settings/post-orders/", views.company_post_orders, name="company_post_orders"),
    path("healthz", views.health, name="health"), path("readyz",views.ready,name="ready"), path("theme.css",views.theme_css,name="theme_css"), path("logo",views.brand_logo,name="brand_logo"), path("manifest.webmanifest", views.manifest, name="manifest"),
    path("service-worker.js", views.service_worker, name="service_worker"),
    path("", workspace_views.workspace_today, name="dashboard"), path("people/", views.people, name="people"),
    path("team/", views.team, name="team"), path("team/<int:membership_id>/authority/", views.authority, name="authority"), path("team/<int:membership_id>/access/", views.membership_access, name="membership_access"), path("team/authority/<int:scope_id>/revoke/", views.authority_revoke, name="authority_revoke"), path("invitations/<str:token>/", views.invitation_accept, name="invitation_accept"),
    path("people/new/", views.person_create, name="person_create"), path("people/fields/new/",views.custom_field_create,name="custom_field_create"),path("people/fields/<int:field_id>/edit/",views.custom_field_edit,name="custom_field_edit"),path("people/fields/<int:field_id>/remove/",views.custom_field_remove,name="custom_field_remove"),path("people/<uuid:person_id>/",views.person_detail,name="person_detail"),path("people/<uuid:person_id>/edit/",views.person_edit,name="person_edit"), path("people/<uuid:person_id>/access/new/",views.person_access_invite,name="person_access_invite"), path("people/<uuid:person_id>/access/link/",views.person_access_link,name="person_access_link"), path("branches/", views.branches, name="branches"), path("branches/new/", views.branch_create, name="branch_create"), path("branches/<int:branch_id>/edit/", views.branch_edit, name="branch_edit"),
    path("people/<uuid:person_id>/credentials/new/", views.credential_create, name="person_credential_create"), path("people/<uuid:person_id>/training/new/", views.training_create, name="person_training_create"), path("people/<uuid:person_id>/documents/new/", views.document_upload, name="person_document_upload"),
    path("settings/", views.settings, name="settings"), path("settings/compliance/", views.settings_compliance, name="settings_compliance"),
    # CMP-1: drafting the Texas duties is an act the operator takes, not a migration that happens to them.
    path("settings/compliance/texas/draft/", views.compliance_seed_texas, name="compliance_seed_texas"),
    path("settings/onboarding/", views.onboarding_settings, name="onboarding_settings"), path("settings/onboarding/new/", views.onboarding_item_edit, name="onboarding_item_create"), path("settings/onboarding/issue/", views.onboarding_issue, name="onboarding_issue"), path("settings/onboarding/<int:item_id>/", views.onboarding_item_edit, name="onboarding_item_edit"), path("people/<uuid:person_id>/onboarding/", views.onboarding_issue, name="person_onboarding_issue"), path("onboarding/tasks/<uuid:task_id>/decide/", views.onboarding_task_decide, name="onboarding_task_decide"), path("my-onboarding/", views.my_onboarding, name="my_onboarding"),
    path("credentials/<uuid:credential_id>/registry/", views.credential_registry_check, name="credential_registry_check"),
    path("settings/pay-categories/", views.settings_pay_categories, name="settings_pay_categories"), path("settings/pay-categories/<int:category_id>/", views.pay_category_edit, name="pay_category_edit"), path("settings/pay-categories/premium/", views.time_policy_premium, name="time_policy_premium"), path("schedule/<uuid:shift_id>/hours/", views.shift_hours, name="shift_hours"), path("schedule/<uuid:shift_id>/hours/save/", views.shift_hours_save, name="shift_hours_save"), path("schedule/<uuid:shift_id>/hours/hold-over/", views.shift_hold_over, name="shift_hold_over"),
    path("settings/branding/", views.branding, name="branding"), path("settings/branding/<int:version_id>/rollback/",views.brand_rollback,name="brand_rollback"),
    path("locations/", views.locations, name="locations"), path("locations/clients/new/", views.client_create, name="client_create"), path("locations/clients/<uuid:client_id>/edit/", views.client_edit, name="client_edit"), path("locations/sites/new/", views.site_create, name="site_create"), path("locations/sites/<uuid:site_id>/edit/", views.site_edit, name="site_edit"), path("locations/sites/<uuid:site_id>/checkpoints/new/", views.checkpoint_create, name="checkpoint_create"), path("checkpoints/<uuid:checkpoint_id>/edit/", views.checkpoint_edit, name="checkpoint_edit"),
    path("compliance/", views.compliance, name="compliance"), path("reports/", views.reports, name="reports"), path("reports/saved/", views.saved_reports, name="saved_reports"), path("reports/save/", views.report_capture, name="report_capture"), path("reports/saved/<uuid:snapshot_id>/download/", views.report_snapshot_download, name="report_snapshot_download"), path("compliance/types/new/", views.credential_type_create, name="credential_type_create"), path("compliance/types/<int:type_id>/edit/", views.credential_type_edit, name="credential_type_edit"), path("compliance/rules/new/", views.compliance_rule_create, name="compliance_rule_create"), path("compliance/rules/<int:rule_id>/edit/", views.compliance_rule_edit, name="compliance_rule_edit"), path("compliance/rules/<int:rule_id>/remove/", views.compliance_rule_remove, name="compliance_rule_remove"), path("compliance/credentials/new/", views.credential_create, name="credential_create"), path("compliance/credentials/<uuid:credential_id>/edit/", views.credential_edit, name="credential_edit"),
    path("schedule/", views.schedule, name="schedule"), path("schedule/new/", views.shift_create, name="shift_create"), path("schedule/<uuid:shift_id>/edit/", views.shift_edit, name="shift_edit"), path("schedule/<uuid:shift_id>/cancel/", views.shift_cancel, name="shift_cancel"), path("schedule/<uuid:shift_id>/requests/", views.shift_requests, name="shift_requests"), path("schedule/claims/<uuid:claim_id>/decide/", views.shift_claim_decide, name="shift_claim_decide"),
    path("schedule/templates/", views.shift_templates, name="shift_templates"), path("schedule/templates/new/", views.shift_template_create, name="shift_template_create"), path("schedule/templates/<uuid:template_id>/", views.shift_template_generate, name="shift_template_generate"), path("schedule/templates/<uuid:template_id>/edit/", views.shift_template_edit, name="shift_template_edit"), path("schedule/templates/<uuid:template_id>/pause/", views.shift_template_pause, name="shift_template_pause"), path("schedule/templates/<uuid:template_id>/remove/", views.shift_template_remove, name="shift_template_remove"),
    path("schedule/swaps/", views.swaps, name="swaps"), path("schedule/swaps/<uuid:swap_id>/decide/", views.swap_decide, name="swap_decide"),
    path("open-posts/", views.open_posts, name="open_posts"), path("open-posts/claim/", views.shift_claim, name="shift_claim"), path("open-posts/claims/<uuid:claim_id>/withdraw/", views.shift_claim_withdraw, name="shift_claim_withdraw"),
    path("my-shifts/", views.my_shifts, name="my_shifts"), path("my-shifts/<uuid:shift_id>/offer/", views.offer_post, name="offer_post"), path("my-shifts/swaps/<uuid:swap_id>/respond/", views.swap_respond, name="swap_respond"), path("my-shifts/swaps/<uuid:swap_id>/withdraw/", views.swap_withdraw, name="swap_withdraw"),
    path("my-shifts/exchanges/<uuid:exchange_id>/respond/", views.exchange_respond, name="exchange_respond"), path("my-shifts/exchanges/<uuid:exchange_id>/withdraw/", views.exchange_withdraw, name="exchange_withdraw"), path("schedule/exchanges/<uuid:exchange_id>/decide/", views.exchange_decide, name="exchange_decide"),
    path("availability/", views.availability, name="availability"), path("people/<uuid:person_id>/availability/", views.availability, name="person_availability"), path("availability/<int:rule_id>/remove/", views.availability_remove, name="availability_remove"),
    path("my-time-off/", views.my_time_off, name="my_time_off"), path("my-time-off/<uuid:request_id>/cancel/", views.my_time_off_cancel, name="my_time_off_cancel"), path("time-off/", views.time_off, name="time_off"), path("time-off/<uuid:request_id>/decide/", views.time_off_decide, name="time_off_decide"),
    path("clock/", views.clock, name="clock"), path("api/punches/", views.punch_api, name="punch_api"), path("api/clock-devices/enroll/",views.clock_device_enroll,name="clock_device_enroll"),path("api/offline-punches/sync/",views.offline_punch_sync,name="offline_punch_sync"),
    path("clock/pin/", views.clock_pin_settings, name="clock_pin"), path("clock/kiosks/", views.clock_kiosks, name="clock_kiosks"), path("clock/kiosks/<uuid:kiosk_id>/close/", views.clock_kiosk_close, name="clock_kiosk_close"), path("clock/kiosks/<uuid:kiosk_id>/clear/", views.clock_kiosk_clear, name="clock_kiosk_clear"),
    path("kiosk/<uuid:kiosk_id>/", views.clock_kiosk, name="kiosk"), path("api/kiosk/<uuid:kiosk_id>/identify/", views.clock_kiosk_identify, name="kiosk_identify"), path("api/kiosk/<uuid:kiosk_id>/punch/", views.clock_kiosk_punch, name="kiosk_punch"),
    # CLK-1. The frame is filed before the punch that names it, on the officer's own device only: a
    # station punch is exempt from the photo rule because its PIN already proved who stood there.
    path("clock/selfie/", views.clock_selfie_upload, name="clock_selfie_upload"),
    path("people/<uuid:person_id>/pin/", views.person_pin_issue, name="person_pin_issue"),
    path("settings/time/", views.time_policy, name="time_policy"), path("settings/time/history/", views.rule_history, name="rule_history"), path("settings/time/history/<str:kind>/", views.rule_history, name="rule_history_kind"), path("settings/time/history/<str:kind>/<str:rule_id>/", views.rule_history, name="rule_history_rule"), path("settings/time/rules/new/", views.time_policy_override, name="time_policy_override_create"), path("settings/time/rules/<int:override_id>/", views.time_policy_override, name="time_policy_override"), path("settings/time/rules/<int:override_id>/remove/", views.time_policy_override_remove, name="time_policy_override_remove"), path("payroll/export/", views.payroll_export, name="payroll_export"),
    path("documents/",views.documents,name="documents"),path("documents/types/new/",views.document_type_create,name="document_type_create"),path("documents/types/<int:type_id>/edit/",views.document_type_edit,name="document_type_edit"),path("documents/types/<int:type_id>/remove/",views.document_type_remove,name="document_type_remove"),path("documents/upload/",views.document_upload,name="document_upload"),path("documents/<uuid:document_id>/download/",views.document_download,name="document_download"),path("documents/<uuid:document_id>/preview/",views.document_preview,name="document_preview"),path("documents/<uuid:document_id>/acknowledgments/",views.document_acknowledgments,name="document_acknowledgments"),path("documents/<uuid:document_id>/remind/",views.document_remind,name="document_remind"),
    path("my-documents/",views.my_documents,name="my_documents"),path("my-documents/<uuid:document_id>/acknowledge/",views.document_acknowledge,name="document_acknowledge"),path("people/<uuid:person_id>/export/",views.person_export,name="person_export"),
    path("documents/retention/",views.retention_review,name="retention_review"),path("documents/<uuid:document_id>/disposition/",views.disposition_request,name="disposition_request"),path("documents/<uuid:document_id>/restore/",views.document_restore,name="document_restore"),path("documents/<uuid:document_id>/legal-hold/",views.legal_hold_toggle,name="legal_hold_toggle"),path("documents/dispositions/<uuid:request_id>/execute/",views.disposition_execute,name="disposition_execute"),
    path("training/",views.training,name="training"),path("training/new/",views.training_create,name="training_create"),path("training/<uuid:record_id>/edit/",views.training_edit,name="training_edit"),
    path("imports/",views.imports,name="imports"),path("imports/templates/<str:entity>.csv",views.import_template,name="import_template"),path("imports/<uuid:batch_id>/errors.csv",views.import_errors,name="import_errors"),path("imports/<uuid:batch_id>/apply/",views.import_apply,name="import_apply"),
    path("notifications/",views.notifications,name="notifications"),path("notifications/<uuid:notification_id>/read/",views.notification_read,name="notification_read"),
    path("notifications/text/", views.text_alerts, name="text_alerts"), path("me/", views.my_account, name="my_account"), path("about/", views.about, name="about"), path("me/contact/", views.my_contact_edit, name="my_contact_edit"), path("settings/messaging/", views.messaging_settings, name="messaging_settings"), path("settings/messaging/rotate/", views.messaging_rotate_token, name="messaging_rotate_token"),
    # NTF-1's per-audience channel rules. Add and edit share one view because the form is the same
    # shape and a second copy of it is how the two drift apart.
    path("settings/messaging/rules/", views.messaging_rule_save, name="messaging_rule_add"),
    path("settings/messaging/rules/<uuid:rule_id>/", views.messaging_rule_save, name="messaging_rule_edit"),
    path("settings/messaging/rules/<uuid:rule_id>/remove/", views.messaging_rule_remove, name="messaging_rule_remove"),
    path("settings/messaging/wording/", views.sms_templates, name="sms_templates"),
    path("settings/messaging/texts/", views.sms_templates, name="sms_templates_legacy"),
    path("settings/messaging/wording/email/<str:notice_key>/", views.email_template_edit, name="email_template_edit"),
    path("settings/messaging/texts/<str:notice_key>/", views.sms_template_edit, name="sms_template_edit"),
    # NTF-4's one operator-performed step: an SNS subscription stays unpublished until somebody clicks
    # its confirmation, because the address to fetch arrives inside an unauthenticated body.
    path("settings/messaging/subscriptions/<uuid:event_id>/confirm/", views.messaging_confirm_subscription, name="messaging_confirm_subscription"),
    path("webhooks/<str:provider>/<str:token>/", views.provider_callback, name="provider_callback"),
    path("time/review/",views.time_review,name="time_review"),path("time/punches/<uuid:punch_id>/review/",views.punch_review,name="punch_review"),path("time/punches/<uuid:punch_id>/correction/",views.adjustment_request,name="adjustment_request"),path("time/adjustments/<uuid:adjustment_id>/review/",views.adjustment_review,name="adjustment_review"),
    path("payroll/",views.payroll,name="payroll"),path("payroll/codes/",views.pay_codes,name="pay_codes"),path("payroll/codes/new/",views.pay_code_create,name="pay_code_create"),path("payroll/codes/<int:code_id>/edit/",views.pay_code_edit,name="pay_code_edit"),path("payroll/codes/<int:code_id>/remove/",views.pay_code_remove,name="pay_code_remove"),path("payroll/<uuid:run_id>/approve/",views.payroll_approve,name="payroll_approve"),path("payroll/<uuid:run_id>/reopen/",views.payroll_reopen,name="payroll_reopen"),path("payroll/<uuid:run_id>/lock/",views.payroll_segment_lock,name="payroll_segment_lock"),path("payroll/<uuid:run_id>/export/",views.payroll_run_export,name="payroll_run_export"),
    path("settings/security/",views.security_settings,name="security_settings"),
    path("organizations/select/",views.tenant_select,name="tenant_select"),path("settings/domains/",views.domains,name="domains"),path("settings/domains/<int:domain_id>/verify/",views.domain_verify,name="domain_verify"),path("platform/",views.platform_admin,name="platform_admin"),
    path("audit/",views.audit_log,name="audit_log"),path("audit/export/",views.audit_export,name="audit_export"),path("audit/seal/",views.audit_seal_run,name="audit_seal_run"),path("audit/seals/<uuid:seal_id>/verify/",views.audit_seal_verify,name="audit_seal_verify"),path("audit/seals/<uuid:seal_id>/download/",views.audit_seal_download,name="audit_seal_download"),path("audit/<uuid:event_id>/redact/",views.audit_redact,name="audit_redact"),path("audit/redactions/<int:redaction_id>/decide/",views.audit_redaction_decide,name="audit_redaction_decide"),
]
